export const COPY = {
  ru: {
    back: "← Меню",
    account: "Мой аккаунт",
    devices: "Мои входы",
    signOutAll: "Выйти везде",
    notMe: "Это не я",
    signOutConfirm: "Выйти на всех устройствах",
    keepSignedIn: "Оставить как есть",
    accountTitle: "Твой аккаунт BetterFy",
    accountAccess: "Доступ",
    accountEarly: "ранний доступ",
    accountPremium: "Premium до {date}",
    accountSignIns: "Активных входов: {count}",
    devicesNone: "Сейчас нет активных входов. Новый вход начнётся из приложения или с сайта.",
    devicesTitle: "Где ты вошёл",
    deviceKinds: { windows: "Windows", web: "сайт", unknown: "другое" },
    signOutAsk: "Выйти из BetterFy на всех устройствах? Приложению и сайту придётся войти заново. Подтверди, если вход был не твой или устройство потеряно.",
    signedOutAll: "Готово. Все входы закрыты. Чтобы войти снова, открой BetterFy и выбери вход через Telegram.",
    unknownText: "Я отвечаю на кнопки и команды. Вот меню.",
    support: "Поддержка",
    supportBody: "С любым вопросом, ошибкой или оплатой пиши в @BeterHelp. Приложи, что случилось и когда. Не присылай коды входа, токены и данные кошелька.",
    premiumEnding: "Premium заканчивается {date}. Если хочешь не терять доступ, продли его заранее: оставшиеся дни сохранятся.",
    renew: "Продлить доступ",
    welcome: "BetterFy на связи. Здесь выдаём код для входа — без паролей и лишних шагов.",
    issue: "Получить код",
    website: "Открыть сайт",
    language: "English",
    codeTitle: "Твой код BetterFy",
    codeBody: "Введи его в приложении. Код сгорит через 10 минут и сработает только один раз.",
    approved: "Готово. Вход в BetterFy подтверждён.",
    confirmDevice: "Подтвердить вход",
    denyDevice: "Отклонить",
    deviceRequest: "BetterFy запрашивает вход на новом устройстве. Подтверди его только если ты сам открыл приложение.",
    deviceDetails: "Устройство: {platform} · BetterFy {version}\nСтрана запроса: {country}\nЗапрошено: {time} UTC",
    deviceMatch: "Число в окне BetterFy: {code}\nЕсли в приложении другое число или ты не начинал вход — нажми «Отклонить».",
    deviceUnknown: "неизвестно",
    deviceApproved: "Вход подтверждён. Вернись в BetterFy — приложение завершит авторизацию само.",
    deviceDenied: "Запрос отклонён.",
    deviceExpired: "Запрос уже истёк. Открой BetterFy и начни вход заново.",
    help: "Нажми «Получить код», затем введи шесть цифр в BetterFy. Если код истёк — запроси новый. Нужна помощь: @BeterHelp.",
    privateOnly: "Напиши боту в личные сообщения — коды не выдаются в группах.",
    rateLimited: "Слишком много запросов. Подожди несколько минут и попробуй снова.",
    languageChanged: "Язык переключён на русский.",
    privacy: "Мы используем Telegram ID, имя и язык только для профиля BetterFy. Переписки бот не читает.",
    terms: "Покупка открывает Premium на выбранный срок. План на 30 дней продлевается автоматически; отключить продление можно командой /subscription. Возвраты рассматриваются через /paysupport.",
    subscribe: "Выбрать доступ",
    choosePlan: "Выбери срок доступа. 3 и 15 дней оплачиваются один раз. План на 30 дней продлевается автоматически — его можно отключить в любой момент.",
    plans: {
      "3d": { button: "3 дня · 75 ⭐", title: "BetterFy · 3 дня", description: "Три дня Premium-доступа без автопродления." },
      "15d": { button: "15 дней · 225 ⭐", title: "BetterFy · 15 дней", description: "Пятнадцать дней Premium-доступа без автопродления." },
      "30d": { button: "30 дней · 525 ⭐", title: "BetterFy · 30 дней", description: "Тридцать дней Premium-доступа с ежемесячным продлением." },
    },
    subscriptionUnavailable: "Этот план временно недоступен.",
    subscriptionActive: "Premium активен до",
    subscriptionInactive: "Активной подписки нет.",
    subscriptionPaid: "Оплата прошла. Premium уже привязан к твоему профилю BetterFy.",
    subscriptionCancel: "Отключить продление",
    subscriptionCanceled: "Автопродление отключено. Доступ останется до конца оплаченного периода.",
    paymentRejected: "Заказ изменился или устарел. Открой новый счёт в боте.",
    paySupport: "По вопросам оплаты напиши в @BeterHelp и приложи дату платежа. Не отправляй коды входа или данные кошелька.",
    paymentRefunded: "Платёж возвращён. Доступ пересчитан по оставшимся активным периодам.",
  },
  en: {
    back: "← Menu",
    account: "My account",
    devices: "My sign-ins",
    signOutAll: "Sign out everywhere",
    notMe: "Not me",
    signOutConfirm: "Sign out on all devices",
    keepSignedIn: "Keep as is",
    accountTitle: "Your BetterFy account",
    accountAccess: "Access",
    accountEarly: "Early Access",
    accountPremium: "Premium until {date}",
    accountSignIns: "Active sign-ins: {count}",
    devicesNone: "There are no active sign-ins right now. A new one starts from the app or the website.",
    devicesTitle: "Where you are signed in",
    deviceKinds: { windows: "Windows", web: "website", unknown: "other" },
    signOutAsk: "Sign out of BetterFy on every device? The app and the site will ask you to sign in again. Confirm if this sign-in was not you or a device is lost.",
    signedOutAll: "Done. Every sign-in is closed. To come back, open BetterFy and choose Telegram sign-in.",
    unknownText: "I answer to buttons and commands. Here is the menu.",
    support: "Support",
    supportBody: "For any question, bug or payment, message @BeterHelp. Say what happened and when. Never send sign-in codes, tokens or wallet details.",
    premiumEnding: "Premium ends on {date}. To keep access, renew early: the days you have left are kept.",
    renew: "Renew access",
    welcome: "BetterFy here. Get a sign-in code — no password, no extra steps.",
    issue: "Get a code",
    website: "Open website",
    language: "Русский",
    codeTitle: "Your BetterFy code",
    codeBody: "Enter it in the app. It expires in 10 minutes and works once.",
    approved: "Done. Your BetterFy sign-in is approved.",
    confirmDevice: "Approve sign-in",
    denyDevice: "Deny",
    deviceRequest: "BetterFy is requesting a sign-in on a new device. Approve it only if you opened the app yourself.",
    deviceDetails: "Device: {platform} · BetterFy {version}\nRequested from: {country}\nRequested at: {time} UTC",
    deviceMatch: "Number in the BetterFy window: {code}\nIf the app shows a different number or you did not start a sign-in, tap Deny.",
    deviceUnknown: "unknown",
    deviceApproved: "Sign-in approved. Return to BetterFy — the app will finish automatically.",
    deviceDenied: "The request was denied.",
    deviceExpired: "This request has expired. Open BetterFy and start sign-in again.",
    help: "Tap “Get a code”, then enter the six digits in BetterFy. Request a new one if it expires. Need help: @BeterHelp.",
    privateOnly: "Message the bot directly — codes are never issued in group chats.",
    rateLimited: "Too many requests. Wait a few minutes and try again.",
    languageChanged: "Language switched to English.",
    privacy: "We use your Telegram ID, name, and language for your BetterFy profile. The bot cannot read your chats.",
    terms: "A purchase unlocks Premium for the selected period. The 30-day plan renews automatically; use /subscription to stop renewal. Refund requests are handled through /paysupport.",
    subscribe: "Choose access",
    choosePlan: "Choose an access period. The 3-day and 15-day passes are one-time purchases. The 30-day plan renews automatically and can be stopped at any time.",
    plans: {
      "3d": { button: "3 days · 75 ⭐", title: "BetterFy · 3 days", description: "Three days of Premium access with no renewal." },
      "15d": { button: "15 days · 225 ⭐", title: "BetterFy · 15 days", description: "Fifteen days of Premium access with no renewal." },
      "30d": { button: "30 days · 525 ⭐", title: "BetterFy · 30 days", description: "Thirty days of Premium access with monthly renewal." },
    },
    subscriptionUnavailable: "This plan is temporarily unavailable.",
    subscriptionActive: "Premium is active until",
    subscriptionInactive: "There is no active subscription.",
    subscriptionPaid: "Payment received. Premium is now linked to your BetterFy profile.",
    subscriptionCancel: "Stop renewal",
    subscriptionCanceled: "Renewal is off. Access remains active until the paid period ends.",
    paymentRejected: "This order changed or expired. Open a new invoice in the bot.",
    paySupport: "For payment support, message @BeterHelp with the payment date. Never send sign-in codes or wallet credentials.",
    paymentRefunded: "The payment was refunded. Access was recalculated from the remaining active periods.",
  },
};
