export const COPY = {
  ru: {
    welcome: "BetterFy на связи. Здесь выдаём код для входа — без паролей и лишних шагов.",
    issue: "Получить код",
    website: "Открыть сайт",
    language: "English",
    codeTitle: "Твой код BetterFy",
    codeBody: "Введи его в приложении. Код сгорит через 10 минут и сработает только один раз.",
    approved: "Готово. Вход в BetterFy подтверждён.",
    help: "Нажми «Получить код», затем введи шесть цифр в BetterFy. Если код истёк — запроси новый.",
    privateOnly: "Напиши боту в личные сообщения — коды не выдаются в группах.",
    rateLimited: "Слишком много запросов. Подожди несколько минут и попробуй снова.",
    languageChanged: "Язык переключён на русский.",
    privacy: "Мы используем Telegram ID, имя и язык только для профиля BetterFy. Переписки бот не читает.",
    terms: "Покупка открывает Premium на выбранный срок. План на 30 дней продлевается автоматически; отключить продление можно командой /subscription. Возвраты рассматриваются через /paysupport.",
    subscribe: "Выбрать доступ",
    choosePlan: "Выбери срок доступа. 3 и 15 дней оплачиваются один раз. План на 30 дней продлевается автоматически — его можно отключить в любой момент.",
    plans: {
      "3d": { button: "3 дня · 75 ⭐", title: "BetterFy · 3 дня", description: "Три дня Premium-доступа без автопродления." },
      "15d": { button: "15 дней · 225 ⭐", title: "BetterFy · 15 дней", description: "Пятнадцать дней Premium-доступа без автопродления." },
      "30d": { button: "30 дней · 525 ⭐", title: "BetterFy · 30 дней", description: "Тридцать дней Premium-доступа с ежемесячным продлением." },
    },
    subscriptionUnavailable: "Этот план временно недоступен.",
    subscriptionActive: "Premium активен до",
    subscriptionInactive: "Активной подписки нет.",
    subscriptionPaid: "Оплата прошла. Premium уже привязан к твоему профилю BetterFy.",
    subscriptionCancel: "Отключить продление",
    subscriptionCanceled: "Автопродление отключено. Доступ останется до конца оплаченного периода.",
    paymentRejected: "Заказ изменился или устарел. Открой новый счёт в боте.",
    paySupport: "По вопросам оплаты напиши @BeterFyBot и приложи дату платежа. Не отправляй коды входа или данные кошелька.",
    paymentRefunded: "Платёж возвращён. Доступ пересчитан по оставшимся активным периодам.",
  },
  en: {
    welcome: "BetterFy here. Get a sign-in code — no password, no extra steps.",
    issue: "Get a code",
    website: "Open website",
    language: "Русский",
    codeTitle: "Your BetterFy code",
    codeBody: "Enter it in the app. It expires in 10 minutes and works once.",
    approved: "Done. Your BetterFy sign-in is approved.",
    help: "Tap “Get a code”, then enter the six digits in BetterFy. Request a new one if it expires.",
    privateOnly: "Message the bot directly — codes are never issued in group chats.",
    rateLimited: "Too many requests. Wait a few minutes and try again.",
    languageChanged: "Language switched to English.",
    privacy: "We use your Telegram ID, name, and language for your BetterFy profile. The bot cannot read your chats.",
    terms: "A purchase unlocks Premium for the selected period. The 30-day plan renews automatically; use /subscription to stop renewal. Refund requests are handled through /paysupport.",
    subscribe: "Choose access",
    choosePlan: "Choose an access period. The 3-day and 15-day passes are one-time purchases. The 30-day plan renews automatically and can be stopped at any time.",
    plans: {
      "3d": { button: "3 days · 75 ⭐", title: "BetterFy · 3 days", description: "Three days of Premium access with no renewal." },
      "15d": { button: "15 days · 225 ⭐", title: "BetterFy · 15 days", description: "Fifteen days of Premium access with no renewal." },
      "30d": { button: "30 days · 525 ⭐", title: "BetterFy · 30 days", description: "Thirty days of Premium access with monthly renewal." },
    },
    subscriptionUnavailable: "This plan is temporarily unavailable.",
    subscriptionActive: "Premium is active until",
    subscriptionInactive: "There is no active subscription.",
    subscriptionPaid: "Payment received. Premium is now linked to your BetterFy profile.",
    subscriptionCancel: "Stop renewal",
    subscriptionCanceled: "Renewal is off. Access remains active until the paid period ends.",
    paymentRejected: "This order changed or expired. Open a new invoice in the bot.",
    paySupport: "For payment support, message @BeterFyBot with the payment date. Never send sign-in codes or wallet credentials.",
    paymentRefunded: "The payment was refunded. Access was recalculated from the remaining active periods.",
  },
};
