import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { ArrowDownToLine, ArrowRight, Check, Copy, FileJson, FolderOpen, Layers3, LoaderCircle, Plus, Search, Trash2, Upload } from "lucide-react";
import { modCount, useLocale } from "../i18n";
import { presetBridge, type BetterFyPreset } from "../presets";
import { modById } from "./model";
import { Empty, Media, Modal, PageHead } from "./ui";

export default function Library({ onApply, onSave, onCatalog, notify, revision }: { onApply: (preset: BetterFyPreset) => void; onSave: () => void; onCatalog: () => void; notify: (text: string) => void; revision: number }) {
  const { language, isRu } = useLocale();
  const [presets, setPresets] = useState<BetterFyPreset[]>([]);
  const [tab, setTab] = useState<"local" | "betterfy">("local");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [reload, setReload] = useState(0);
  const [query, setQuery] = useState("");
  const [importing, setImporting] = useState(false);
  const [serialized, setSerialized] = useState("");
  const [transferError, setTransferError] = useState("");
  const [busy, setBusy] = useState(false);
  const [removing, setRemoving] = useState<BetterFyPreset | null>(null);
  const file = useRef<HTMLInputElement>(null);
  useEffect(() => { let active = true; setLoading(true); setError(false); presetBridge.list().then(items => { if (active) setPresets(items); }).catch(() => { if (active) setError(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [reload, revision]);
  const items = presets.filter(preset => preset.source === tab && preset.name.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  const exportPreset = async (preset: BetterFyPreset) => {
    try { const value = await presetBridge.export(preset); const url = URL.createObjectURL(new Blob([value], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${preset.name.replace(/[^\p{L}\p{N} _-]/gu, "").slice(0, 60) || "betterfy-build"}.json`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); notify(isRu ? "Набор экспортирован" : "Build exported"); } catch { notify(isRu ? "Не удалось экспортировать набор" : "Could not export the build"); }
  };
  const importPreset = async () => { setBusy(true); setTransferError(""); try { await presetBridge.import(serialized); setReload(value => value + 1); setTab("local"); setImporting(false); setSerialized(""); notify(isRu ? "Набор добавлен в библиотеку" : "Build added to your library"); } catch { setTransferError(isRu ? "Не удалось прочитать конфиг BetterFy. Проверь файл и попробуй снова." : "Could not read this BetterFy config. Check the file and try again."); } finally { setBusy(false); } };
  const readFile = async (event: ChangeEvent<HTMLInputElement>) => { const selectedFile = event.target.files?.[0]; if (!selectedFile) return; if (selectedFile.size > 1024 * 1024) { setTransferError(isRu ? "Размер конфига не должен превышать 1 МБ" : "Config must be smaller than 1 MB"); return; } try { setSerialized(await selectedFile.text()); setTransferError(""); } catch { setTransferError(isRu ? "Не удалось открыть файл" : "Could not open the file"); } };
  return <div className="s-library"><PageHead title={isRu ? "Твоя библиотека" : "Your library"} description={isRu ? "Сохраняй любимые наборы и возвращайся к ним когда угодно." : "Keep your favorite builds and come back to them anytime."}><button className="s-btn" onClick={() => setImporting(true)}><Upload />{isRu ? "Импорт" : "Import"}</button><button className="s-btn s-btn-primary" onClick={onSave}><Plus />{isRu ? "Сохранить набор" : "Save build"}</button></PageHead>
    <div className="s-library-tools"><div className="s-domain-tabs" role="tablist" aria-label={isRu ? "Источник наборов" : "Build source"}><button role="tab" aria-selected={tab === "local"} onClick={() => setTab("local")}>{isRu ? "Мои наборы" : "My builds"}<span>{presets.filter(p => p.source === "local").length}</span></button><button role="tab" aria-selected={tab === "betterfy"} onClick={() => setTab("betterfy")}>{isRu ? "Подборки BetterFy" : "BetterFy collections"}</button></div><label className="s-search"><Search /><input aria-label={isRu ? "Поиск наборов" : "Search builds"} placeholder={isRu ? "Найти набор" : "Find a build"} value={query} onChange={event => setQuery(event.target.value)} /></label></div>
    {loading ? <div className="s-loading-inline" role="status"><LoaderCircle className="s-spin" />{isRu ? "Открываем библиотеку" : "Opening your library"}</div> : error ? <Empty icon={<FolderOpen />} title={isRu ? "Библиотека недоступна" : "Library unavailable"} text={isRu ? "Не удалось прочитать локальные наборы." : "We could not read your saved builds."} action={isRu ? "Попробовать снова" : "Try again"} onAction={() => setReload(value => value + 1)} /> : items.length ? <div className="s-preset-grid">{items.map(preset => { const ids = [...preset.modIds, ...preset.wardrobeIds]; const previews = ids.flatMap(id => { const mod = modById.get(id); return mod?.image ? [mod] : []; }).slice(0, 3); return <article className="s-preset-card" key={preset.id}><button className="s-preset-art" onClick={() => onApply(preset)} aria-label={`${isRu ? "Открыть набор" : "Open build"}: ${preset.name}`}>{previews.length ? previews.map(mod => <Media key={mod.id} src={mod.image ?? undefined} loading="lazy" />) : <Layers3 />}<span>{modCount(ids.length, language)}</span></button><div className="s-preset-content"><h2>{preset.name}</h2><p>{new Intl.DateTimeFormat(language === "ru" ? "ru-RU" : "en-GB", { day: "numeric", month: "short" }).format(new Date(preset.updatedAt))}</p><footer><button className="s-btn" onClick={() => onApply(preset)}>{isRu ? "Открыть набор" : "Open build"}<ArrowRight /></button><button className="s-icon" aria-label={`${isRu ? "Экспортировать" : "Export"}: ${preset.name}`} onClick={() => void exportPreset(preset)}><ArrowDownToLine /></button>{!preset.readOnly && <button className="s-icon" aria-label={`${isRu ? "Удалить" : "Delete"}: ${preset.name}`} onClick={() => setRemoving(preset)}><Trash2 /></button>}</footer></div></article>; })}</div> : <Empty icon={<FolderOpen />} title={query ? (isRu ? "Набор не найден" : "No matching builds") : (isRu ? "Здесь будут твои любимые наборы" : "A home for your favorite builds")} text={isRu ? "Выбери моды, сохрани набор и дай ему имя. Или импортируй конфиг друга." : "Choose mods, save a build and give it a name. Or import a friend's config."} action={isRu ? "Выбрать моды" : "Choose mods"} onAction={onCatalog} />}
    {importing && <Modal title={isRu ? "Импорт набора" : "Import build"} onClose={() => { if (!busy) setImporting(false); }}><div className="s-dialog-body"><p>{isRu ? "Открой JSON-файл BetterFy или вставь его содержимое." : "Open a BetterFy JSON file or paste its contents."}</p><input ref={file} type="file" accept=".json,application/json" hidden onChange={event => void readFile(event)} /><button className="s-file-drop" onClick={() => file.current?.click()}><FileJson /><strong>{isRu ? "Выбрать файл" : "Choose file"}</strong><span>JSON · {isRu ? "до 1 МБ" : "up to 1 MB"}</span></button><label className="s-field"><span>{isRu ? "Содержимое конфига" : "Config contents"}</span><textarea value={serialized} onChange={event => setSerialized(event.target.value)} placeholder='{"schemaVersion": 1, ...}' spellCheck={false} /></label>{transferError && <p className="s-form-error" role="alert">{transferError}</p>}<button className="s-btn s-btn-primary s-btn-full" disabled={!serialized.trim() || busy} onClick={() => void importPreset()}>{busy ? <LoaderCircle className="s-spin" /> : <Upload />}{isRu ? "Добавить в библиотеку" : "Add to library"}</button></div></Modal>}
    {removing && <Modal title={isRu ? "Удалить сохранённый набор?" : "Delete saved build?"} onClose={() => setRemoving(null)}><div className="s-dialog-body"><p>«{removing.name}». {isRu ? "Текущая сборка и файлы игры останутся без изменений." : "Your current selection and game files will stay unchanged."}</p><div className="s-dialog-actions"><button className="s-btn" onClick={() => setRemoving(null)}>{isRu ? "Оставить" : "Keep it"}</button><button className="s-btn s-btn-danger" onClick={async () => { try { await presetBridge.remove(removing.id); setRemoving(null); setReload(v => v + 1); } catch { notify(isRu ? "Не удалось удалить набор" : "Could not delete build"); } }}>{isRu ? "Удалить набор" : "Delete build"}</button></div></div></Modal>}
  </div>;
}
