import { Fragment, useEffect, useRef, useState } from "react";
import { AlertTriangle, ArrowDownToLine, ArrowRight, Check, ChevronRight, CircleUserRound, Download, ExternalLink, FileCheck2, Gamepad2, KeyRound, Layers3, LogOut, Mail, Menu, Monitor, Moon, PackageCheck, Plus, RotateCcw, Search, Send, ShieldCheck, Sparkles, Sun, UserRound, WifiOff, X } from "lucide-react";
import Ambient from "./Ambient";
import "./spotlight";

type Language = "ru" | "en";
type AuthStage = "idle" | "checking" | "code" | "verifying" | "ready" | "unavailable";
type ReleaseState = "idle" | "loading" | "ready" | "missing" | "unavailable";
type WebSession = { userId:string; displayName:string; username?:string; accessTier:string; accessExpiresAt?:number; sessionId?:string; avatarAvailable:boolean };
type DeviceSession = { sessionId:string; clientKind:"web"|"desktop"|"unknown"; lastUsedAt:number; expiresAt:number; current:boolean };
type ReleaseMeta = { version:string; fileName:string; size:number; publishedAt:string; prerelease:boolean };
type GithubRelease = { tag_name?:string; name?:string; published_at?:string; draft?:boolean; prerelease?:boolean; assets?:Array<{name?:string;size?:number}> };

const repo = "https://github.com/zori-xyz/BetterFy";
const bot = "https://t.me/BeterFyBot?start=web_login";
const authUrl = import.meta.env.VITE_BETTERFY_AUTH_URL || "https://betterfy-auth.zori-xyz.workers.dev";
const sessionKey = "betterfy:web-session";
const asset = (name:string) => `${import.meta.env.BASE_URL}${name}`;
// Same choice as the auth worker's resolver: a stable release first, else the
// newest Early Access pre-release, BetterFy Setup before the older NSIS name.
const installerNames = ["BetterFy-Setup.exe", "BetterFy-Windows-x64-setup.exe"];
export const releasesUrl = "https://api.github.com/repos/zori-xyz/BetterFy/releases?per_page=20";

const copy = {
  ru: {
    nav:["Возможности","Как работает","Скачать"], early:"РАННИЙ ДОСТУП", profile:"Профиль", light:"Светлая", dark:"Тёмная", open:"Открыть", menu:"Меню", close:"Закрыть", skip:"Перейти к содержанию",
    hero:{tag:"DOTA 2 · МОДЫ И ОБЛИКИ",a:"Твоя Dota.",b:"Только лучше.",body:"Облики героев, эффекты и настройки игры в одном приложении. Четыре мода уже ставятся в Dota с проверкой файлов и откатом, остальное можно собирать в наборы.",cta:"Посмотреть приложение",download:"Скачать для Windows",status:"Early Access · Windows x64",slides:[{label:"Обзор",text:"Главная со сборкой и витриной обликов"},{label:"Каталог",text:"1 135 обликов и эффектов с превью"},{label:"Моя сборка",text:"Шаги установки и откат в одном месте"}]},
    stats:[{value:1135,label:"обликов и эффектов в каталоге"},{value:30,label:"модов настройки игры"},{value:4,label:"мода ставятся с проверкой и откатом"},{value:2,label:"языковых слота Dota проверены на Windows"}],
    product:{tag:"ВНУТРИ ПРИЛОЖЕНИЯ",a:"Два каталога.",b:"Одна сборка.",body:"Настройка игры отвечает за производительность и игровые инструменты, облики — за героев, интерфейс, эффекты и звук. Всё выбранное собирается в один набор."},
    minify:{tag:"НАСТРОЙКА ИГРЫ · MINIFY",a:"Настрой игру.",b:"Без ручной рутины.",body:"Моды из открытого проекта dota2-minify: убрать реку, показать networth, упростить деревья. Моды с отметкой «Windows-пилот» ставятся в Dota с проверкой и откатом.",items:["Шесть категорий и поиск","Автор и источник на каждой карточке","Порядок модов решает, кто главнее"],link:"Как проходит установка"},
    wardrobe:{tag:"ОБЛИКИ И ЭФФЕКТЫ",a:"Настрой внешний",b:"вид игры.",body:"1 135 вариантов для героев, интерфейса, мира, эффектов и звука. Их можно смотреть и собирать в наборы; установка обликов в Dota появится в следующих сборках.",items:["Поиск по герою и категории","Живое превью варианта","Светлая и тёмная тема приложения"]},
    proof:{tag:"WINDOWS-ПИЛОТ",a:"Видно не только,",b:"что выбрано.",body:"Перед установкой BetterFy показывает, что именно будет записано в Dota, в каком порядке и где лежит резервная копия. Откат доступен сразу после установки.",facts:[["4","мода проверены в игре на Windows"],["2","языковых слота: русский и нидерландский"],["1","итоговый файл модов в выбранном порядке"],["SHA-256","у каждого скачанного ресурса"]],note:"Каталог обликов пока работает как превью. Устанавливаются только моды с отметкой «Windows-пилот».",open:"Открыть экран сборки"},
    journey:{tag:"КАК РАБОТАЕТ BETTERFY",a:"От выбора",b:"до запуска.",body:"Четыре коротких шага. На каждом видно, что происходит со сборкой и что делать дальше.",next:"Следующий шаг",restart:"Начать сначала"},
    account:{tag:"ПРОФИЛЬ BETTERFY",player:"Игрок",offline:"Вход не выполнен",setup:"Настроить",browser:"Этот браузер",browserState:"Вход ещё не выполнен",current:"ТЕКУЩИЙ",app:"Приложение Windows",appState:"Подключается отдельно",notConnected:"НЕ ПОДКЛЮЧЕНО",section:"ПРОФИЛЬ И УСТРОЙСТВА",a:"Доступ рядом.",b:"Устройства под контролем.",body:"BetterFy ID для сайта и приложения: вход по никнейму или почте с паролем. Telegram остаётся быстрым отдельным способом.",open:"Открыть профиль"},
    download:{tag:"WINDOWS · РАННИЙ ДОСТУП",a:"BetterFy для",b:"Windows.",body:"Сборки Early Access выходят как pre-release на GitHub. Здесь видны версия, дата и размер установщика.",cta:"Скачать BetterFy",check:"Скачать для Windows",versions:"Все версии на GitHub",title:"BetterFy для Windows",checking:"Ищем актуальную сборку Early Access.",ready:"Сборка найдена. Для скачивания войди в BetterFy ID.",readySigned:"Сборка найдена и готова к скачиванию.",missingLead:"Как только сборка выйдет, здесь появятся версия, дата и размер.",offlineLead:"Сейчас не получилось проверить сборку.",system:"Windows x64",found:"Сборка найдена",login:"Войди в BetterFy ID",continue:"Войти и продолжить",error:"Не удалось открыть сборку. Попробуй ещё раз.",version:"ВЕРСИЯ",package:"РАЗМЕР",published:"ОБНОВЛЕНО",locating:"Ищем последнюю сборку…",unavailable:"Публичная сборка ещё не выпущена",network:"Не удалось связаться с GitHub. Проверь сеть и повтори.",retry:"Повторить",prerelease:"Early Access · pre-release"},
    auth:{tag:"BETTERFY ID",title:"Твой BetterFy ID",body:"Войди с паролем или через Telegram.",id:"Войти через BetterFy ID",telegram:"Войти через Telegram",identifier:"Почта или никнейм",username:"Никнейм латиницей",password:"Пароль — от 12 символов",create:"Создать BetterFy ID",forgot:"Забыл пароль? Получить код на почту",registerNote:"Подтверди почту кодом из письма.",email:"Адрес почты",send:"Получить код",emailCode:"Код из письма",emailNote:"Если почта подключена, письмо придёт в течение минуты. Код действует 10 минут.",first:"Для входа с паролем создай BetterFy ID. Telegram — отдельный быстрый вход.",link:"Подключить почту",linked:"Почта подключена",linkNote:"Подтверди адрес, чтобы входить с ним в тот же профиль BetterFy.",back:"Назад",retry:"Попробовать ещё раз",access:"ДОСТУП",notConnected:"Не подключён",sessions:"СЕССИИ",none:"Нет активных",code:"КОД",minutes:"10 минут",get:"Получить код в Telegram",have:"У меня уже есть код",label:"Код подтверждения",enter:"Войти",oneTime:"Код одноразовый и действует 10 минут.",safe:"Профиль под контролем.",safeText:"Способы входа не объединяются автоматически. Активные сеансы можно завершить здесь.",security:"Безопасность",source:"Исходный код",checking:"Проверяем…",invalid:"Проверь данные и попробуй ещё раз.",offline:"Сервис авторизации сейчас недоступен. Твоя локальная сессия сохранена.",storage:"Вход выполнен только для этой вкладки: браузер запретил сохранение сессии.",active:"Активные устройства",until:"до",revoke:"Завершить",signout:"Выйти",early:"Ранний доступ",premium:"Premium"},
    footer:{tag:"Твоя Dota. Только лучше.",product:"Продукт",project:"Проект",features:"Возможности",process:"Как работает",telegram:"Telegram",roadmap:"Планы",legal:"Независимый проект. Не связан с Valve Corporation."}
  },
  en: {
    nav:["Features","How it works","Download"], early:"EARLY ACCESS", profile:"Profile", light:"Light", dark:"Dark", open:"Open", menu:"Menu", close:"Close", skip:"Skip to content",
    hero:{tag:"DOTA 2 · MODS AND LOOKS",a:"Your Dota.",b:"Only better.",body:"Hero looks, effects and game tuning in one app. Four mods already install into Dota with file checks and rollback; everything else can be collected into sets.",cta:"See the app",download:"Download for Windows",status:"Early Access · Windows x64",slides:[{label:"Overview",text:"Home with your build and a look showcase"},{label:"Catalog",text:"1,135 looks and effects with previews"},{label:"My build",text:"Install steps and rollback in one place"}]},
    stats:[{value:1135,label:"looks and effects in the catalog"},{value:30,label:"game tuning mods"},{value:4,label:"mods install with checks and rollback"},{value:2,label:"Dota language slots verified on Windows"}],
    product:{tag:"INSIDE THE APP",a:"Two catalogs.",b:"One build.",body:"Game tuning covers performance and game tools; looks cover heroes, interface, effects and audio. Everything you pick comes together in one set."},
    minify:{tag:"GAME TUNING · MINIFY",a:"Tune the game.",b:"Skip the manual work.",body:"Mods from the open dota2-minify project: remove the river, show net worth, simplify trees. Mods marked Windows pilot install into Dota with checks and rollback.",items:["Six categories and search","Author and source on every card","Mod order decides which one wins"],link:"How installation works"},
    wardrobe:{tag:"LOOKS AND EFFECTS",a:"Shape the look",b:"of your game.",body:"1,135 options for heroes, interface, world, effects and audio. You can browse them and collect sets; installing looks into Dota comes in later builds.",items:["Search by hero and category","Live preview of the variant","Light and dark app themes"]},
    proof:{tag:"WINDOWS PILOT",a:"See more than",b:"what you picked.",body:"Before installing, BetterFy shows exactly what will be written to Dota, in which order, and where the backup lives. Restore is available right after installation.",facts:[["4","mods verified in game on Windows"],["2","language slots: Russian and Dutch"],["1","final mod file in your chosen order"],["SHA-256","for every downloaded resource"]],note:"The looks catalog is preview-only for now. Only mods marked Windows pilot install.",open:"Open the build screen"},
    journey:{tag:"HOW BETTERFY WORKS",a:"From selection",b:"to launch.",body:"Four short steps. At each one, you know what is happening and what comes next.",next:"Next step",restart:"Start again"},
    account:{tag:"BETTERFY PROFILE",player:"Player",offline:"Not signed in",setup:"Set up",browser:"This browser",browserState:"Not signed in yet",current:"CURRENT",app:"Windows app",appState:"Connects separately",notConnected:"NOT CONNECTED",section:"PROFILE AND DEVICES",a:"Access stays close.",b:"Devices stay in view.",body:"BetterFy ID for the site and app: use a username or email and password. Telegram remains a separate quick option.",open:"Open profile"},
    download:{tag:"WINDOWS · EARLY ACCESS",a:"BetterFy for",b:"Windows.",body:"Early Access builds are published as GitHub pre-releases. The version, date and installer size appear here.",cta:"Download BetterFy",check:"Download for Windows",versions:"All versions on GitHub",title:"BetterFy for Windows",checking:"Looking for the current Early Access build.",ready:"Build found. Sign in to BetterFy ID to download.",readySigned:"Build found and ready to download.",missingLead:"As soon as a build is out, its version, date and size appear here.",offlineLead:"The build could not be checked right now.",system:"Windows x64",found:"Build found",login:"Sign in to BetterFy ID",continue:"Sign in and continue",error:"The build could not be opened. Please try again.",version:"VERSION",package:"SIZE",published:"UPDATED",locating:"Looking for the latest build…",unavailable:"No public build has been released yet",network:"GitHub could not be reached. Check your connection and try again.",retry:"Try again",prerelease:"Early Access · pre-release"},
    auth:{tag:"BETTERFY ID",title:"Your BetterFy ID",body:"Use a password or sign in through Telegram.",id:"Sign in with BetterFy ID",telegram:"Sign in with Telegram",identifier:"Email or username",username:"Username",password:"Password — at least 12 characters",create:"Create BetterFy ID",forgot:"Forgot password? Get an email code",registerNote:"Verify your email with the code we send.",email:"Email address",send:"Send a code",emailCode:"Email code",emailNote:"If the email is linked, the message will arrive shortly. The code is valid for 10 minutes.",first:"Create BetterFy ID for password sign-in. Telegram is a separate quick option.",link:"Link an email",linked:"Email linked",linkNote:"Verify an address to sign in to this same BetterFy profile.",back:"Back",retry:"Try again",access:"ACCESS",notConnected:"Not connected",sessions:"SESSIONS",none:"No active sessions",code:"CODE",minutes:"10 minutes",get:"Get a code in Telegram",have:"I already have a code",label:"Confirmation code",enter:"Sign in",oneTime:"The code is single-use and valid for 10 minutes.",safe:"You stay in control.",safeText:"Sign-in methods are not merged automatically. End active sessions here anytime.",security:"Security",source:"Source code",checking:"Checking…",invalid:"Check your details and try again.",offline:"The sign-in service is unavailable. Your local session has been kept.",storage:"Signed in for this tab only because the browser blocked session storage.",active:"Active devices",until:"until",revoke:"End",signout:"Sign out",early:"Early access",premium:"Premium"},
    footer:{tag:"Your Dota. Only better.",product:"Product",project:"Project",features:"Features",process:"How it works",telegram:"Telegram",roadmap:"Roadmap",legal:"Independent project. Not affiliated with Valve Corporation."}
  }
} as const;

const journeyCopy = {
  ru:[
    {n:"01",title:"Выбрать",label:"два каталога",heading:"Собери свой набор.",text:"Настройка игры и облики живут в отдельных каталогах. У каждой карточки есть превью, автор и источник.",points:["Фильтры по типу и герою","Превью до добавления","Выбор сохраняется сразу"],icon:Search},
    {n:"02",title:"Проверить",label:"до установки",heading:"Узнай результат заранее.",text:"BetterFy скачивает только проверенные файлы модов, сверяет каждый и показывает порядок: если два мода меняют одно и то же, побеждает верхний.",points:["Файлы сверяются по SHA-256","Порядок модов на виду","Понятный итог проверки"],icon:FileCheck2},
    {n:"03",title:"Установить",label:"с бэкапом",heading:"Поставь одним планом.",text:"Четыре пилотных мода установлены и проверены в Dota на Windows через русский и нидерландский языковые слоты, на одной машине. Общая установка из каталога пока закрыта.",points:["Бэкап перед записью","Статус каждого шага","Отчёт о каждой операции"],icon:PackageCheck},
    {n:"04",title:"Откатить",label:"по журналу",heading:"Сохрани путь назад.",text:"Откат пилотной сборки подтверждён на Windows. Журнал не даёт BetterFy затереть изменения, которые сделал кто-то другой.",points:["Проверка перед откатом","Чужие изменения блокируют откат","Откат доступен в один клик"],icon:RotateCcw}
  ],
  en:[
    {n:"01",title:"Select",label:"two catalogs",heading:"Choose your setup.",text:"Game tuning and looks live in separate catalogs. Every card has a preview, an author and a source.",points:["Filters by type and hero","Preview before adding","Selection saves instantly"],icon:Search},
    {n:"02",title:"Check",label:"before install",heading:"Know the result first.",text:"BetterFy downloads only verified mod files, checks each one and shows the order: when two mods change the same thing, the higher one wins.",points:["Files checked by SHA-256","Mod order stays visible","A clear check summary"],icon:FileCheck2},
    {n:"03",title:"Install",label:"with a backup",heading:"Install from one plan.",text:"Four pilot mods have been installed and checked in Dota on Windows through the Russian and Dutch language slots, on one machine. General catalog installation stays closed for now.",points:["Backup before writing","Status for every step","A report for every operation"],icon:PackageCheck},
    {n:"04",title:"Restore",label:"from the journal",heading:"Keep a way back.",text:"Restoring the pilot build has been confirmed on Windows. The journal keeps BetterFy from overwriting changes someone else made.",points:["Check before restoring","Outside edits block a restore","Restore in one click"],icon:RotateCcw}
  ]
} as const;

const Wordmark=({compact=false,onFy}:{compact?:boolean;onFy?:()=>void})=><span className={`wordmark ${compact?"compact":""}`} aria-label="BetterFy"><span className="wordmark-better">Better</span><span className="wordmark-fy" onClick={onFy}>Fy</span></span>;

function pickRelease(releases:GithubRelease[]):ReleaseMeta|null{
  const available=releases.filter(release=>release&&release.draft!==true);
  const installer=(release:GithubRelease)=>{for(const name of installerNames){const found=release.assets?.find(item=>item?.name===name&&item.size);if(found)return found}return null};
  const release=available.find(item=>item.prerelease!==true&&installer(item))??available.find(item=>item.prerelease===true&&installer(item));
  const file=release&&installer(release);
  if(!release||!file?.name||!file.size||!release.tag_name||!release.published_at)return null;
  return {version:release.tag_name,fileName:file.name,size:file.size,publishedAt:release.published_at,prerelease:release.prerelease===true};
}
function safeReleaseUrl(value?:string){try{if(!value)return null;const url=new URL(value);return url.protocol==="https:"&&url.hostname==="github.com"&&url.pathname.startsWith("/zori-xyz/BetterFy/releases/")?url.toString():null}catch{return null}}
function readStorage(storage:"local"|"session",key:string){try{return (storage==="local"?localStorage:sessionStorage).getItem(key)}catch{return null}}
function writeSession(key:string,value:string){try{sessionStorage.setItem(key,value);return true}catch{return false}}
function removeSession(key:string){try{sessionStorage.removeItem(key)}catch{}}
const reducedMotion=()=>typeof window!=="undefined"&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;

// Counts up once the number scrolls into view.
function CountUp({value,locale}:{value:number;locale:string}){
  const ref=useRef<HTMLSpanElement>(null),[shown,setShown]=useState(()=>reducedMotion()||typeof IntersectionObserver==="undefined"?value:0);
  useEffect(()=>{const node=ref.current;if(!node||reducedMotion()||typeof IntersectionObserver==="undefined"){setShown(value);return}let frame=0;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();const start=performance.now();const step=(time:number)=>{const progress=Math.min(1,(time-start)/1300);setShown(Math.round(value*(1-(1-progress)**4)));if(progress<1)frame=requestAnimationFrame(step)};frame=requestAnimationFrame(step)},{threshold:.4});observer.observe(node);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value]);
  return <span ref={ref}>{shown.toLocaleString(locale)}</span>;
}

// Small live fragments of the app for each journey step.
function StepScene({index,language}:{index:number;language:Language}){
  const ru=language==="ru";
  if(index===0)return <div className="scene scene-select" aria-hidden="true">{(ru?[["Убрать реку","Карта и мир"],["Показывать свой Net Worth","HUD и меню"],["Упрощённые деревья","Карта и мир"]]:[["Remove River","Map & world"],["Show NetWorth","HUD & menus"],["Tree Mod","Map & world"]]).map(([name,cat],i)=><div className={`mini-card ${i===1?"is-picked":""}`} key={name}><i style={{backgroundImage:`url(${asset(`site-minify-${language}.webp`)})`,backgroundPosition:`${20+i*30}% 75%`}}/><small>{cat}</small><b>{name}</b><span>{i===1?<Check size={13}/>:<Plus size={13}/>}</span></div>)}</div>;
  if(index===1)return <div className="scene scene-check" aria-hidden="true">{[["Tree Mod","21 / 21"],["Show NetWorth","1 / 1"],["Remove River","23 / 23"]].map(([name,count],i)=><div className="plan-row" key={name} style={{animationDelay:`${i*.35}s`}}><span>{String(i+1).padStart(2,"0")}</span><b>{name}</b><small>SHA-256 · {count}</small><i><Check size={13}/></i></div>)}<p>{ru?"Если два мода меняют один файл, побеждает верхний.":"When two mods change one file, the higher one wins."}</p></div>;
  if(index===2)return <div className="scene scene-install" aria-hidden="true">{(ru?["Бэкап","Загрузка","Проверка","Готово"]:["Backup","Download","Verify","Done"]).map((label,i)=><div className="install-step" key={label} style={{animationDelay:`${i*.9}s`}}><i>{String(i+1).padStart(2,"0")}</i><span>{label}</span></div>)}<div className="install-bar"><i/></div></div>;
  return <div className="scene scene-restore" aria-hidden="true"><code><b>backupVerified</b> true</code><code><b>phase</b> rolled_back</code><code><b>rollbackVerified</b> true</code><span className="restore-badge"><RotateCcw size={15}/>{ru?"Игра как была":"Game restored"}</span></div>;
}

function ProfilePanel({language,t,close,stage,session,token,onEmailSignedIn,code,setCode,error,storageWarning,verify,avatar,sessions,revoke,logout}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;stage:AuthStage;session:WebSession|null;token:string|null;onEmailSignedIn:(data:WebSession&{sessionToken:string})=>void;code:string;setCode:(v:string)=>void;error:string;storageWarning:boolean;verify:()=>void;avatar:string|null;sessions:DeviceSession[];revoke:(s:DeviceSession)=>void;logout:()=>void}){
  const access=session?.accessTier==="premium"?t.auth.premium:t.auth.early;
  const[emailMode,setEmailMode]=useState<"choice"|"address"|"code">("choice"),[email,setEmail]=useState(""),[emailCode,setEmailCode]=useState(""),[emailBusy,setEmailBusy]=useState(false),[emailError,setEmailError]=useState(""),[emailIdentity,setEmailIdentity]=useState<{linked:boolean;emailHint:string|null}|null>(null);
  const[idMode,setIdMode]=useState<"choice"|"login"|"register"|"register-code">("choice"),[identifier,setIdentifier]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[idBusy,setIdBusy]=useState(false),[idError,setIdError]=useState("");
  const idRequest=async(path:string,payload:object)=>{const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),credentials:"omit"});if(!response.ok)throw new Error();return response.json()};
  const submitId=async()=>{setIdBusy(true);setIdError("");try{if(idMode==="register"){await idRequest("/v1/auth/id/register/start",{username,email,password,language});setPassword("");setEmailCode("");setIdMode("register-code");return}const path=idMode==="login"?"/v1/auth/id/login":"/v1/auth/id/register/verify";const data=await idRequest(path,idMode==="login"?{identifier,password,clientKind:"web"}:{email,code:emailCode,clientKind:"web"});if(!data.sessionToken||!data.displayName)throw new Error();setPassword("");onEmailSignedIn(data);setIdMode("choice")}catch{setIdError(t.auth.invalid)}finally{setIdBusy(false)}};
  useEffect(()=>{if(!token)return;const controller=new AbortController();fetch(new URL("/v1/session/email",authUrl),{headers:{Authorization:`Bearer ${token}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setEmailIdentity(data)).catch(()=>{});return()=>controller.abort()},[token]);
  const startEmail=async()=>{setEmailBusy(true);setEmailError("");try{const path=session?"/v1/session/email/start":"/v1/auth/email/start";const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json",...(session&&token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({email,language}),credentials:"omit"});if(!response.ok)throw new Error();setEmailMode("code");setEmailCode("")}catch{setEmailError(t.auth.offline)}finally{setEmailBusy(false)}};
  const verifyEmail=async()=>{setEmailBusy(true);setEmailError("");try{const path=session?"/v1/session/email/verify":"/v1/auth/email/verify";const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json",...(session&&token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({email,code:emailCode,...(!session?{clientKind:"web"}:{})}),credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json();if(session){setEmailIdentity({linked:true,emailHint:data.emailHint});setEmailMode("choice")}else if(data.sessionToken&&data.displayName){onEmailSignedIn(data);setEmailMode("choice")}else throw new Error()}catch{setEmailError(t.auth.invalid)}finally{setEmailBusy(false)}};
  return <div className="modal-backdrop" onMouseDown={close}><section className="profile-panel" role="dialog" aria-modal="true" aria-labelledby="profile-title" onMouseDown={e=>e.stopPropagation()}>
    <button className="modal-close" onClick={close} aria-label={t.close}><X size={17}/></button>
    <div className="profile-head"><div className="profile-avatar">{avatar?<img src={avatar} alt=""/>:<UserRound size={34}/>}<span>BF</span></div><div><p className="micro">{t.auth.tag}</p><h2 id="profile-title">{session?session.displayName:t.auth.title}</h2><p>{session?(session.username?`@${session.username} · ${access}`:access):t.auth.body}</p></div></div>
    {storageWarning&&<p className="status-note warning" role="status"><AlertTriangle size={16}/>{t.auth.storage}</p>}
    {stage==="unavailable"&&!session&&<p className="status-note error" role="alert"><WifiOff size={16}/>{t.auth.offline}</p>}
    {!session&&idMode!=="choice"&&<form className="site-id-form" onSubmit={e=>{e.preventDefault();void submitId()}}><button className="site-id-back" type="button" onClick={()=>{setIdMode("choice");setIdError("")}}>{t.auth.back}</button><h3>{idMode==="login"?t.auth.id:idMode==="register"?t.auth.create:t.auth.emailCode}</h3>{idMode==="register"&&<p>{t.auth.registerNote}</p>}{idMode==="login"&&<input aria-label={t.auth.identifier} autoComplete="username" required maxLength={254} placeholder={t.auth.identifier} value={identifier} onChange={e=>setIdentifier(e.target.value)}/ >}{idMode==="register"&&<><input aria-label={t.auth.username} autoComplete="username" required minLength={3} maxLength={24} pattern="[A-Za-z][A-Za-z0-9_]{2,23}" placeholder={t.auth.username} value={username} onChange={e=>setUsername(e.target.value)}/><input aria-label={t.auth.email} type="email" autoComplete="email" required maxLength={254} placeholder={t.auth.email} value={email} onChange={e=>setEmail(e.target.value)}/></>}{(idMode==="login"||idMode==="register")&&<input aria-label={t.auth.password} type="password" autoComplete={idMode==="register"?"new-password":"current-password"} required minLength={12} maxLength={128} placeholder={t.auth.password} value={password} onChange={e=>setPassword(e.target.value)}/ >}{idMode==="register-code"&&<><p>{t.auth.registerNote}</p><input aria-label={t.auth.emailCode} inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength={6} value={emailCode} onChange={e=>setEmailCode(e.target.value.replace(/\D/g,"").slice(0,6))}/></>}{idError&&<small role="alert" className="is-error">{idError}</small>}<button className="site-id-primary" disabled={idBusy||(idMode==="register-code"&&emailCode.length!==6)}>{idBusy?t.auth.checking:idMode==="login"?t.auth.enter:idMode==="register"?t.auth.create:t.auth.emailCode}<ArrowRight size={16}/></button>{idMode==="login"&&<><button className="site-id-back" type="button" onClick={()=>setIdMode("register")}>{t.auth.create}</button><button className="site-id-back" type="button" onClick={()=>{setEmail(identifier.includes("@")?identifier:"");setIdMode("choice");setEmailMode("address")}}>{t.auth.forgot}</button></>}</form>}
    {idMode==="choice"&&emailMode!=="choice"&&<form className="site-id-form" onSubmit={e=>{e.preventDefault();void(emailMode==="address"?startEmail():verifyEmail())}}><button className="site-id-back" type="button" onClick={()=>{setEmailMode("choice");setEmailError("")}}>{t.auth.back}</button><h3>{emailMode==="address"?t.auth.email:t.auth.emailCode}</h3><p>{emailMode==="address"?session?t.auth.linkNote:t.auth.first:t.auth.emailNote}</p>{emailMode==="address"?<input aria-label={t.auth.email} type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/>:<input aria-label={t.auth.emailCode} type="text" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={emailCode} onChange={e=>setEmailCode(e.target.value.replace(/\D/g,"").slice(0,6))}/ >}{emailError&&<small role="alert" className="is-error">{emailError}</small>}<button className="site-id-primary" disabled={emailBusy||(emailMode==="code"&&emailCode.length!==6)}>{emailBusy?t.auth.checking:emailMode==="address"?t.auth.send:t.auth.enter}<ArrowRight size={16}/></button>{emailMode==="code"&&<button className="site-id-back" type="button" disabled={emailBusy} onClick={()=>void startEmail()}>{t.auth.retry}</button>}</form>}
    {idMode==="choice"&&emailMode==="choice"&&(session?<>
      <div className="profile-summary"><div><ShieldCheck size={18}/><span>{t.auth.access}</span><strong>{access}</strong></div><div><Monitor size={18}/><span>{t.auth.sessions}</span><strong>{sessions.length}</strong></div><div><KeyRound size={18}/><span>ID</span><strong>{session.userId.slice(0,8)}</strong></div></div>
      <div className="site-id-link"><span className="site-id-icon"><Mail size={20}/></span><div><b>{language==="ru"?"Почта для входа по коду":"Email code sign-in"}</b><small>{emailIdentity?.linked?`${t.auth.linked} · ${emailIdentity.emailHint}`:t.auth.linkNote}</small></div>{!emailIdentity?.linked&&emailMode==="choice"&&<button type="button" onClick={()=>setEmailMode("address")}>{t.auth.link}<ArrowRight size={15}/></button>}</div>
      <div className="device-list"><h3>{t.auth.active}</h3>{sessions.map(item=><article key={item.sessionId}><span className="device-icon">{item.clientKind==="desktop"?<Gamepad2 size={17}/>:<Monitor size={17}/>}</span><div><b>{item.clientKind==="desktop"?"BetterFy Windows":language==="ru"?"Веб-сайт BetterFy":"BetterFy website"}</b><small>{t.auth.until} {new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(item.expiresAt*1000))}</small></div>{item.current?<em>{t.account.current}</em>:<button onClick={()=>revoke(item)}>{t.auth.revoke}</button>}</article>)}</div>
      <button className="signout-button" onClick={logout}><LogOut size={15}/>{t.auth.signout}</button>
    </>:<>
      {emailMode==="choice"&&<div className="site-id-choices"><button className="site-id-primary" type="button" onClick={()=>setIdMode("login")}><KeyRound size={18}/><b>{t.auth.id}</b><ArrowRight size={17}/></button><a className="site-id-telegram" href={bot} target="_blank" rel="noreferrer" onClick={()=>setCode("")}><Send size={18}/><b>{t.auth.telegram}</b><ExternalLink size={16}/></a><p>{t.auth.first}</p></div>}
      {emailMode==="choice"&&stage==="idle"&&<button className="have-code-button" type="button" onClick={()=>setCode("")}><KeyRound size={14}/>{t.auth.have}</button>}
      {(stage==="code"||stage==="verifying")&&<form className="code-row otp-form" onSubmit={e=>{e.preventDefault();verify()}}><label htmlFor="access-code">{t.auth.label}</label><div className="code-entry"><div className="otp-control"><div className="otp-slots" aria-hidden="true">{Array.from({length:6},(_,index)=><span key={index} className={code.length===index?"current":""}>{code[index]||""}</span>)}</div><input className="otp-input" id="access-code" aria-label={t.auth.label} inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} disabled={stage==="verifying"}/></div><button className="otp-submit" type="submit" disabled={stage==="verifying"||code.length!==6}>{stage==="verifying"?t.auth.checking:t.auth.enter}<ArrowRight size={15}/></button></div><small className={error?"is-error":""}>{error||t.auth.oneTime}</small></form>}
      <div className="profile-note"><ShieldCheck size={16}/><p><b>{t.auth.safe}</b><span>{t.auth.safeText}</span></p></div>
    </>)}
    <div className="profile-links"><a href={`${repo}/blob/main/docs/IDENTITY_AND_WEB_ARCHITECTURE.md`}>{t.auth.security}<ExternalLink size={12}/></a><a href={repo}>{t.auth.source}<ExternalLink size={12}/></a></div>
  </section></div>
}

function DownloadPanel({language,t,close,session,release,releaseState,retry,openProfile,download,error}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;session:WebSession|null;release:ReleaseMeta|null;releaseState:ReleaseState;retry:()=>void;openProfile:()=>void;download:()=>void;error:string}){
  const date=release?new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(release.publishedAt)):"-";
  const size=release?`${(release.size/1048576).toFixed(1)} MB`:"-";
  const loading=releaseState==="loading";
  const lead=loading||releaseState==="idle"?t.download.checking:release?(session?t.download.readySigned:t.download.ready):releaseState==="unavailable"?t.download.offlineLead:t.download.missingLead;
  return <div className="modal-backdrop" onMouseDown={close}><section className="download-panel" role="dialog" aria-modal="true" aria-labelledby="download-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close} aria-label={t.close}><X size={17}/></button><div className="download-mark"><Wordmark/></div><p className="micro">{t.download.tag}</p><h2 id="download-title">{t.download.title}</h2><p>{lead}</p><div className="download-checks"><span className="active"><i><Monitor size={14}/></i>{t.download.system}</span><span className={release?"active":releaseState==="unavailable"?"error":""}><i>{release?<Check size={14}/>:releaseState==="unavailable"?<WifiOff size={14}/>:"2"}</i>{loading?t.download.locating:release?t.download.found:releaseState==="unavailable"?t.download.network:t.download.unavailable}</span><span className={session?"active":""}><i>{session?<Check size={14}/>:"3"}</i>{session?session.displayName:t.download.login}</span></div>{release&&<div className="release-details"><span><small>{t.download.version}</small><b>{release.version}</b></span><span><small>{t.download.package}</small><b title={release.fileName}>{size}</b></span><span><small>{t.download.published}</small><b>{date}</b></span></div>}{release?.prerelease&&<p className="release-note">{t.download.prerelease}</p>}{releaseState==="unavailable"&&<button className="retry-button" onClick={retry}>{t.download.retry}</button>}<button className="action primary wide" onClick={session?download:openProfile} disabled={loading||(Boolean(session)&&!release)}><span className="action-icon">{session?<ArrowDownToLine size={17}/>:<CircleUserRound size={17}/>}</span><b>{session?t.download.cta:t.download.continue}</b><ArrowRight size={17}/></button>{error&&<p className="download-error" role="alert">{error}</p>}<a className="quiet-link" href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></section></div>
}

export default function Site(){
  const[language,setLanguage]=useState<Language>("ru"),[profile,setProfile]=useState(false),[download,setDownload]=useState(false),[mobileMenu,setMobileMenu]=useState(false),[active,setActive]=useState(0),[darkWardrobe,setDarkWardrobe]=useState(true),[slide,setSlide]=useState(0),[slidePaused,setSlidePaused]=useState(false),[preview,setPreview]=useState<{src:string;alt:string}|null>(null),[fyClicks,setFyClicks]=useState(0);
  const[authStage,setAuthStage]=useState<AuthStage>("checking"),[authSession,setAuthSession]=useState<WebSession|null>(null),[sessionToken,setSessionToken]=useState<string|null>(null),[authCode,setAuthCode]=useState(""),[authError,setAuthError]=useState(""),[storageWarning,setStorageWarning]=useState(false),[avatarUrl,setAvatarUrl]=useState<string|null>(null),[deviceSessions,setDeviceSessions]=useState<DeviceSession[]>([]),[downloadError,setDownloadError]=useState(""),[releaseMeta,setReleaseMeta]=useState<ReleaseMeta|null>(null),[releaseState,setReleaseState]=useState<ReleaseState>("idle"),[releaseAttempt,setReleaseAttempt]=useState(0);
  const returnFocus=useRef<HTMLElement|null>(null),langRef=useRef<HTMLDivElement>(null),tabsRef=useRef<HTMLDivElement>(null),[langPill,setLangPill]=useState<{left:number;width:number}|null>(null),[tabPill,setTabPill]=useState<{left:number;top:number;width:number;height:number}|null>(null);
  const t=copy[language],steps=journeyCopy[language],step=steps[active],locale=language==="ru"?"ru-RU":"en-GB";
  const modalOpen=profile||download||Boolean(preview);
  const slides=[`site-hero-${language}.webp`,`site-catalog-${language}.webp`,`site-build-${language}.webp`].map(asset);
  const wardrobeImage=asset(`site-wardrobe-${language}-${darkWardrobe?"dark":"light"}.webp`);
  const minifyImage=asset(`site-minify-${language}.webp`);
  const buildImage=asset(`site-build-${language}.webp`);

  useEffect(()=>{const saved=readStorage("local","betterfy-site-language");if(saved==="en")setLanguage("en");const stored=readStorage("session",sessionKey);if(stored)setSessionToken(stored);else setAuthStage("idle")},[]);
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem("betterfy-site-language",language)}catch{}},[language]);
  useEffect(()=>{if(!modalOpen)return;returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const background=[document.querySelector<HTMLElement>(".site-header"),document.querySelector<HTMLElement>("main")].filter((node):node is HTMLElement=>Boolean(node));background.forEach(node=>{node.inert=true;node.setAttribute("aria-hidden","true")});document.body.style.overflow="hidden";const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setProfile(false);setDownload(false);setPreview(null);return}if(event.key!=="Tab")return;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');if(!dialog)return;const focusable=Array.from(dialog.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(node=>node.offsetParent!==null);if(focusable.length===0){event.preventDefault();dialog.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("keydown",onKey);background.forEach(node=>{node.inert=false;node.removeAttribute("aria-hidden")});document.body.style.overflow="";returnFocus.current?.focus();returnFocus.current=null}},[modalOpen]);
  useEffect(()=>{if(!modalOpen)return;const frame=requestAnimationFrame(()=>document.querySelector<HTMLElement>('[role="dialog"] .modal-close')?.focus());return()=>cancelAnimationFrame(frame)},[modalOpen,profile,download,preview]);
  useEffect(()=>{if(!mobileMenu)return;const closeMenu=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setMobileMenu(false);requestAnimationFrame(()=>document.querySelector<HTMLElement>(".menu-button")?.focus())}};window.addEventListener("keydown",closeMenu);return()=>window.removeEventListener("keydown",closeMenu)},[mobileMenu]);
  useEffect(()=>{const nodes=Array.from(document.querySelectorAll<HTMLElement>(".reveal"));if(reducedMotion()||!("IntersectionObserver" in window)||typeof IntersectionObserver==="undefined"){nodes.forEach(n=>n.classList.add("is-visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:"0px 0px -7%"});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);
  // The hero tells the app's story in three screens and moves on by itself.
  useEffect(()=>{if(slidePaused||reducedMotion())return;const timer=window.setTimeout(()=>setSlide(value=>(value+1)%3),6000);return()=>window.clearTimeout(timer)},[slide,slidePaused]);
  // Sliding pills under the language switch and the journey tabs.
  useEffect(()=>{const measure=()=>{const lang=langRef.current?.querySelector<HTMLElement>("button.active");setLangPill(lang?{left:lang.offsetLeft,width:lang.offsetWidth}:null);const tab=tabsRef.current?.querySelector<HTMLElement>('[aria-selected="true"]');setTabPill(tab?{left:tab.offsetLeft,top:tab.offsetTop,width:tab.offsetWidth,height:tab.offsetHeight}:null)};measure();window.addEventListener("resize",measure);return()=>window.removeEventListener("resize",measure)},[language,active]);
  useEffect(()=>{if(fyClicks<5)return;const timer=window.setTimeout(()=>setFyClicks(0),1600);return()=>window.clearTimeout(timer)},[fyClicks]);
  useEffect(()=>{if(!sessionToken){setAuthSession(null);setAuthStage("idle");return}const controller=new AbortController();setAuthStage("checking");fetch(new URL("/v1/session/profile",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(async response=>{if(response.status===401||response.status===403){removeSession(sessionKey);setSessionToken(null);setAuthSession(null);setAuthStage("idle");return null}if(!response.ok)throw new Error("profile_unavailable");return response.json() as Promise<WebSession>}).then(data=>{if(!data)return;setAuthSession(data);setAuthStage("ready")}).catch(e=>{if(e instanceof DOMException&&e.name==="AbortError")return;setAuthStage("unavailable")});return()=>controller.abort()},[sessionToken]);
  useEffect(()=>{if(!sessionToken||!authSession?.avatarAvailable){setAvatarUrl(null);return}const controller=new AbortController();let objectUrl:string|null=null;fetch(new URL("/v1/session/avatar",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.blob():Promise.reject()).then(blob=>{objectUrl=URL.createObjectURL(blob);setAvatarUrl(objectUrl)}).catch(()=>setAvatarUrl(null));return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[sessionToken,authSession?.avatarAvailable]);
  useEffect(()=>{if(!profile||!sessionToken||!authSession)return;const controller=new AbortController();fetch(new URL("/v1/session/devices",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then((data:{sessions?:DeviceSession[]})=>setDeviceSessions(Array.isArray(data.sessions)?data.sessions:[])).catch(()=>setDeviceSessions([]));return()=>controller.abort()},[profile,sessionToken,authSession]);
  useEffect(()=>{if(!download)return;const controller=new AbortController();setReleaseState("loading");fetch(releasesUrl,{headers:{Accept:"application/vnd.github+json"},signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("release_unavailable");return response.json() as Promise<GithubRelease[]>}).then(data=>{const picked=Array.isArray(data)?pickRelease(data):null;if(!picked){setReleaseState("missing");return}setReleaseMeta(picked);setReleaseState("ready")}).catch(()=>{if(!controller.signal.aborted)setReleaseState("unavailable")});return()=>controller.abort()},[download,releaseAttempt]);

  const verifyCode=async()=>{if(!/^\d{6}$/.test(authCode)){setAuthError(t.auth.invalid);return}setAuthStage("verifying");setAuthError("");try{const response=await fetch(new URL("/v1/auth/telegram/code",authUrl),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:authCode,clientKind:"web"}),credentials:"omit"});if(!response.ok)throw new Error("invalid_code");const data=await response.json() as WebSession&{sessionToken?:string};if(!data.sessionToken||!data.displayName)throw new Error("invalid_response");setStorageWarning(!writeSession(sessionKey,data.sessionToken));setSessionToken(data.sessionToken);setAuthSession(data);setAuthStage("ready");setAuthCode("")}catch(error){setAuthStage("code");setAuthError(error instanceof TypeError?t.auth.offline:t.auth.invalid)}};
  const revoke=async(item:DeviceSession)=>{if(!sessionToken)return;try{const response=await fetch(new URL("/v1/session/devices/revoke",authUrl),{method:"POST",headers:{Authorization:`Bearer ${sessionToken}`,"content-type":"application/json"},body:JSON.stringify({sessionId:item.sessionId}),credentials:"omit"});if(!response.ok)throw new Error();if(item.current){logout();return}setDeviceSessions(v=>v.filter(x=>x.sessionId!==item.sessionId))}catch{}};
  const logout=()=>{const token=sessionToken;removeSession(sessionKey);setStorageWarning(false);setSessionToken(null);setAuthSession(null);setAvatarUrl(null);setDeviceSessions([]);setAuthStage("idle");if(token)fetch(new URL("/v1/session/logout",authUrl),{method:"POST",headers:{Authorization:`Bearer ${token}`},credentials:"omit"}).catch(()=>undefined)};
  const downloadBuild=async()=>{setDownloadError("");if(!sessionToken||!authSession){setDownload(false);setProfile(true);return}try{const response=await fetch(new URL("/v1/releases/latest",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json() as{downloadUrl?:string};const url=safeReleaseUrl(data.downloadUrl);if(!url)throw new Error();window.location.assign(url)}catch{setDownloadError(t.download.error)}};

  const closeMobileMenu=()=>setMobileMenu(false);
  const fy=()=>setFyClicks(value=>value+1);
  const slideAlt=t.hero.slides.map(item=>`BetterFy · ${item.label}: ${item.text}`);
  return <><a className="skip-link" href="#content">{t.skip}</a>
  <header className="site-header"><a href="#top" aria-label="BetterFy"><Wordmark compact/></a><nav className="site-nav" aria-label={t.menu}><a href="#product">{t.nav[0]}</a><a href="#journey">{t.nav[1]}</a><a href="#download">{t.nav[2]}</a></nav><div className="header-actions"><div className="language-switch" ref={langRef} role="group" aria-label={language==="ru"?"Язык":"Language"}>{langPill&&<span className="switch-pill" aria-hidden="true" style={{transform:`translateX(${langPill.left-3}px)`,width:langPill.width}}/>}<button aria-pressed={language==="ru"} className={language==="ru"?"active":""} onClick={()=>setLanguage("ru")}>RU</button><button aria-pressed={language==="en"} className={language==="en"?"active":""} onClick={()=>setLanguage("en")}>EN</button></div><span className="live"><i/>{t.early}</span><button className="profile-button" onClick={()=>setProfile(true)}>{avatarUrl?<img src={avatarUrl} alt=""/>:<CircleUserRound size={16}/>} <span>{authSession?.displayName||t.profile}</span></button><button className="menu-button" type="button" aria-label={mobileMenu?t.close:t.menu} aria-expanded={mobileMenu} aria-controls="mobile-navigation" onClick={()=>setMobileMenu(value=>!value)}>{mobileMenu?<X size={19}/>:<Menu size={19}/>}</button></div>{mobileMenu&&<nav className="mobile-navigation" id="mobile-navigation" aria-label={t.menu}><a href="#product" onClick={closeMobileMenu}>{t.nav[0]}</a><a href="#journey" onClick={closeMobileMenu}>{t.nav[1]}</a><a href="#download" onClick={closeMobileMenu}>{t.nav[2]}</a><button onClick={()=>{closeMobileMenu();setProfile(true)}}>{t.profile}</button></nav>}</header>
  <main id="content">
    <section id="top" className="hero-wrap"><Ambient/><div className="hero shell"><div className="hero-copy"><p className="eyebrow"><Sparkles size={13}/>{t.hero.tag}</p><h1>{t.hero.a}<br/><strong>{t.hero.b}</strong></h1><p className="lead">{t.hero.body}</p><div className="hero-actions"><button className="action primary" onClick={()=>document.querySelector("#product")?.scrollIntoView({behavior:reducedMotion()?"auto":"smooth"})}><span className="action-icon"><Layers3 size={18}/></span><b>{t.hero.cta}</b><ArrowRight size={18}/></button><button className="text-action" onClick={()=>setDownload(true)}>{t.hero.download}<Download size={15}/></button></div><p className="hero-status"><i/>{t.hero.status}</p></div>
      <div className="hero-showcase" onMouseEnter={()=>setSlidePaused(true)} onMouseLeave={()=>setSlidePaused(false)} onFocus={()=>setSlidePaused(true)} onBlur={()=>setSlidePaused(false)}><figure className="hero-poster" data-spotlight="tilt"><div className="poster-glow"/>{slides.map((src,index)=><img key={src} src={src} width="1600" height="1000" alt={slideAlt[index]} className={index===slide?"is-current":""} aria-hidden={index!==slide}/>)}<figcaption><span>{t.hero.slides[slide].label}</span><b>{t.hero.slides[slide].text}</b></figcaption></figure><div className="hero-carousel" role="group" aria-label={language==="ru"?"Экраны BetterFy":"BetterFy screens"}>{t.hero.slides.map((item,index)=><button key={item.label} type="button" aria-pressed={slide===index} onClick={()=>setSlide(index)}><span>{String(index+1).padStart(2,"0")}</span><b>{item.label}</b><i aria-hidden="true" className={slide===index&&!slidePaused?"is-running":""}/></button>)}</div></div></div></section>
    <section className="stats shell reveal" aria-label={language==="ru"?"BetterFy в цифрах":"BetterFy in numbers"}>{t.stats.map((item,index)=><div key={item.label} style={{transitionDelay:`${index*.06}s`}}><strong><CountUp value={item.value} locale={locale}/></strong><span>{item.label}</span></div>)}</section>
    <section className="product shell" id="product"><div className="section-intro reveal"><p className="eyebrow">{t.product.tag}</p><h2>{t.product.a}<br/><strong>{t.product.b}</strong></h2><p>{t.product.body}</p></div>
      <article className="feature reveal" data-spotlight><div className="feature-copy"><p className="micro">{t.minify.tag}</p><h3>{t.minify.a}<br/>{t.minify.b}</h3><p>{t.minify.body}</p><ul>{t.minify.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><a href="#journey">{t.minify.link}<ChevronRight size={14}/></a></div><button className="poster-button" onClick={()=>setPreview({src:minifyImage,alt:t.minify.tag})} aria-label={language==="ru"?"Открыть экран настройки игры":"Open the game tuning screen"}><img key={minifyImage} src={minifyImage} width="1720" height="920" loading="lazy" alt={language==="ru"?"Каталог настройки игры в BetterFy":"BetterFy game tuning catalog"}/><span>{t.open}<ExternalLink size={12}/></span></button></article>
      <article className={`feature feature-reverse reveal ${darkWardrobe?"":"is-light"}`} data-spotlight><button className="poster-button" onClick={()=>setPreview({src:wardrobeImage,alt:t.wardrobe.tag})} aria-label={language==="ru"?"Открыть экран обликов":"Open the looks screen"}><img key={wardrobeImage} src={wardrobeImage} width="1536" height="1024" loading="lazy" alt={language==="ru"?"Каталог обликов BetterFy":"BetterFy looks catalog"}/><span>{t.open}<ExternalLink size={12}/></span></button><div className="feature-copy"><div className="theme-switch" role="group" aria-label={language==="ru"?"Тема превью":"Preview theme"}><span className="switch-pill" aria-hidden="true" style={{transform:`translateX(${darkWardrobe?100:0}%)`}}/><button type="button" aria-pressed={!darkWardrobe} className={!darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(false)}><Sun size={13}/>{t.light}</button><button type="button" aria-pressed={darkWardrobe} className={darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(true)}><Moon size={13}/>{t.dark}</button></div><p className="micro">{t.wardrobe.tag}</p><h3>{t.wardrobe.a}<br/>{t.wardrobe.b}</h3><p>{t.wardrobe.body}</p><ul>{t.wardrobe.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></article></section>
    <section className="proof shell" aria-labelledby="proof-title"><div className="proof-copy reveal"><p className="eyebrow"><ShieldCheck size={13}/>{t.proof.tag}</p><h2 id="proof-title">{t.proof.a}<br/><strong>{t.proof.b}</strong></h2><p>{t.proof.body}</p><dl className="proof-facts">{t.proof.facts.map(([value,label])=><div key={label}><dt>{value}</dt><dd>{label}</dd></div>)}</dl><p className="proof-note"><AlertTriangle size={14}/>{t.proof.note}</p></div><button className="poster-button proof-poster reveal" data-spotlight onClick={()=>setPreview({src:buildImage,alt:t.proof.open})} aria-label={t.proof.open}><img key={buildImage} src={buildImage} width="1600" height="1000" loading="lazy" alt={language==="ru"?"Экран «Моя сборка» с шагами установки":"My build screen with installation steps"}/><span>{t.open}<ExternalLink size={12}/></span></button></section>
    <section className="journey" id="journey"><div className="shell"><div className="journey-intro reveal"><p className="eyebrow">{t.journey.tag}</p><h2>{t.journey.a}<br/><strong>{t.journey.b}</strong></h2><p>{t.journey.body}</p></div><div className="journey-board reveal" data-spotlight><div className="journey-tabs" ref={tabsRef} role="tablist" aria-label={t.journey.tag} onKeyDown={event=>{const keys=["ArrowRight","ArrowDown","ArrowLeft","ArrowUp","Home","End"];if(!keys.includes(event.key))return;event.preventDefault();const next=event.key==="Home"?0:event.key==="End"?steps.length-1:event.key==="ArrowRight"||event.key==="ArrowDown"?(active+1)%steps.length:(active-1+steps.length)%steps.length;setActive(next);requestAnimationFrame(()=>document.getElementById(`journey-tab-${next}`)?.focus())}}>{tabPill&&<span className="tab-pill" aria-hidden="true" style={{transform:`translate(${tabPill.left}px,${tabPill.top}px)`,width:tabPill.width,height:tabPill.height}}/>}{steps.map((item,i)=>{const Icon=item.icon;return <button id={`journey-tab-${i}`} key={item.n} role="tab" aria-selected={active===i} aria-controls="journey-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)}><i><Icon size={18}/></i><b>{item.title}</b><small>{item.label}</small></button>})}</div><div id="journey-panel" role="tabpanel" aria-labelledby={`journey-tab-${active}`} tabIndex={0} className="journey-detail" key={`${language}-${step.n}`}><div className="stage-visual"><StepScene index={active} language={language}/></div><div className="stage-copy"><p className="micro">{step.n} · {step.title}</p><h3>{step.heading}</h3><p>{step.text}</p><ul>{step.points.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><button onClick={()=>setActive(active===3?0:active+1)}>{active===3?t.journey.restart:t.journey.next}{active===3?<RotateCcw size={16}/>:<ArrowRight size={16}/>}</button></div></div><div className="journey-progress" aria-hidden="true"><i style={{width:`${25*(active+1)}%`}}/></div></div></div></section>
    <section className="account shell reveal"><div className="account-visual" data-spotlight><div className="account-card"><div className="account-avatar">{avatarUrl?<img src={avatarUrl} alt=""/>:<UserRound size={27}/>}</div><div><p className="micro">{t.account.tag}</p><h3>{authSession?.displayName||t.account.player}</h3><span>{authSession?(authSession.username?`@${authSession.username}`:t.auth.early):t.account.offline}</span></div><button onClick={()=>setProfile(true)}>{t.account.setup}<ArrowRight size={14}/></button></div><div className="session-row"><Monitor size={17}/><div><b>{t.account.browser}</b><span>{authSession?t.auth.safe:t.account.browserState}</span></div>{authSession&&<em>{t.account.current}</em>}</div><div className="session-row"><Gamepad2 size={17}/><div><b>{t.account.app}</b><span>{t.account.appState}</span></div><em className="is-quiet">{t.account.notConnected}</em></div></div><div className="account-copy"><p className="eyebrow">{t.account.section}</p><h2>{t.account.a}<br/><strong>{t.account.b}</strong></h2><p>{t.account.body}</p><button className="action secondary" onClick={()=>setProfile(true)}><span className="action-icon"><CircleUserRound size={18}/></span><b>{t.account.open}</b><ArrowRight size={18}/></button></div></section>
    <section className="download-section" id="download"><div className="shell download-inner reveal" data-spotlight><div><p className="eyebrow">{t.download.tag}</p><h2>{t.download.a}<br/><strong>{t.download.b}</strong></h2><p>{t.download.body}</p></div><div className="download-cta"><button className="action primary huge" onClick={()=>setDownload(true)}><span className="action-icon"><ArrowDownToLine size={19}/></span><b>{t.download.check}</b><ArrowRight size={19}/></button><span>{t.download.system} · {t.download.prerelease}</span><a href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></div></div></section>
    <footer className="site-footer shell"><div><span className={`footer-mark ${fyClicks>=5?"is-party":""}`}><Wordmark onFy={fy}/>{fyClicks>=5&&<span className="fy-burst" aria-hidden="true">{Array.from({length:16},(_,i)=><i key={i} style={{["--a" as string]:`${i*22.5}deg`,["--d" as string]:`${40+(i%3)*16}px`}}/>)}</span>}</span><p>{t.footer.tag}</p></div><div><b>{t.footer.product}</b><a href="#product">{t.footer.features}</a><a href="#journey">{t.footer.process}</a><button onClick={()=>setProfile(true)}>{t.profile}</button></div><div><b>{t.footer.project}</b><a href={repo}>GitHub<ExternalLink size={11}/></a><a href={bot}>{t.footer.telegram}<Send size={11}/></a><a href={`${repo}/blob/main/docs/ROADMAP.md`}>{t.footer.roadmap}<ExternalLink size={11}/></a></div><span>{t.footer.legal}</span></footer>
  </main>
  {profile&&<ProfilePanel language={language} t={t} close={()=>setProfile(false)} stage={authStage} session={authSession} token={sessionToken} onEmailSignedIn={data=>{setStorageWarning(!writeSession(sessionKey,data.sessionToken));setSessionToken(data.sessionToken);setAuthSession(data);setAuthStage("ready")}} code={authCode} setCode={v=>{setAuthCode(v);setAuthError("");setAuthStage("code")}} error={authError} storageWarning={storageWarning} verify={verifyCode} avatar={avatarUrl} sessions={deviceSessions} revoke={revoke} logout={logout}/>} {download&&<DownloadPanel language={language} t={t} close={()=>setDownload(false)} session={authSession} release={releaseMeta} releaseState={releaseState} retry={()=>{setReleaseMeta(null);setReleaseAttempt(value=>value+1)}} openProfile={()=>{setDownload(false);setProfile(true)}} download={downloadBuild} error={downloadError}/>}
  {preview&&<div className="modal-backdrop" onMouseDown={()=>setPreview(null)}><section className="preview-panel" role="dialog" aria-modal="true" aria-label={preview.alt} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setPreview(null)} aria-label={t.close}><X size={17}/></button><img src={preview.src} alt={preview.alt}/></section></div>}
  </>;
}
