import { Fragment, useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { AlertTriangle, ArrowDownToLine, ArrowRight, Check, ChevronRight, CircleUserRound, Download, ExternalLink, FileCheck2, Gamepad2, KeyRound, Layers3, LogOut, Mail, Menu, Monitor, PackageCheck, RotateCcw, Search, Send, ShieldCheck, Sparkles, UserRound, WifiOff, X } from "lucide-react";

type Language = "ru" | "en";
type AuthStage = "idle" | "checking" | "code" | "verifying" | "ready" | "unavailable";
type ReleaseState = "idle" | "loading" | "ready" | "missing" | "unavailable";
type WebSession = { userId:string; displayName:string; username?:string; accessTier:string; accessExpiresAt?:number; sessionId?:string; avatarAvailable:boolean };
type DeviceSession = { sessionId:string; clientKind:"web"|"desktop"|"unknown"; lastUsedAt:number; expiresAt:number; current:boolean };
type ReleaseMeta = { version:string; fileName:string; size:number; publishedAt:string };

const repo = "https://github.com/zori-xyz/BetterFy";
const bot = "https://t.me/BeterFyBot?start=web_login";
const authUrl = import.meta.env.VITE_BETTERFY_AUTH_URL || "https://betterfy-auth.zori-xyz.workers.dev";
const sessionKey = "betterfy:web-session";
const asset = (name:string) => `${import.meta.env.BASE_URL}${name}`;

const copy = {
  ru: {
    nav:["Возможности","Как работает","Скачать"], early:"РАННИЙ ДОСТУП", profile:"Профиль", light:"СВЕТЛАЯ", dark:"ТЁМНАЯ", open:"ОТКРЫТЬ", menu:"Меню", close:"Закрыть", skip:"Перейти к содержанию",
    hero:{tag:"DOTA 2 · ПЛАТФОРМА МОДОВ",a:"Твоя Dota.",b:"Только лучше.",body:"Выбирайте моды и оформление. BetterFy собирает их в один понятный план и показывает конфликты до подтверждения.",cta:"Посмотреть приложение",download:"Проверить сборку Windows",card:"ГЛАВНАЯ",cardText:"Активная сборка всегда перед глазами"},
    rail:[["ВЫБОР","моды и оформление"],["ПРОВЕРКА","файлы и конфликты"],["СБОРКА","готовый набор"],["ЗАПУСК","игра или откат"]],
    product:{tag:"ВНУТРИ ПРИЛОЖЕНИЯ",a:"Два каталога.",b:"Одна сборка.",body:"Minify отвечает за оптимизацию и игровые инструменты. Гардероб отвечает за героев, HUD, эффекты и звук. Выбранное объединяется только на этапе сборки."},
    minify:{tag:"MINIFY · ФУНКЦИОНАЛЬНЫЕ МОДЫ",a:"Настрой игру.",b:"Без ручной рутины.",body:"Карточка объясняет назначение мода, показывает доступные превью, автора и источник.",items:["Поиск и семь категорий","Автор и источник на месте","Конфликт виден до сборки"],link:"Посмотреть процесс"},
    wardrobe:{tag:"ГАРДЕРОБ · ВИЗУАЛЬНЫЕ МОДЫ",a:"Настрой внешний",b:"вид игры.",body:"В каталоге 1 135 вариантов для героев, интерфейса, мира, эффектов и звука. Выбор остаётся на месте при переходе между категориями.",items:["Поиск по герою и категории","Превью выбранного варианта","Совместимость и автор"]},
    journey:{tag:"КАК РАБОТАЕТ BETTERFY",a:"От выбора",b:"до запуска.",body:"Четыре коротких шага. На каждом видно, что происходит со сборкой и что делать дальше.",stage:"ЭТАП",next:"Следующий этап",restart:"Начать сначала"},
    account:{tag:"ПРОФИЛЬ BETTERFY",player:"Игрок",offline:"Вход не выполнен",setup:"Настроить",browser:"Этот браузер",browserState:"Вход ещё не выполнен",current:"ТЕКУЩИЙ",app:"Приложение Windows",appState:"Подключается отдельно",notConnected:"НЕ ПОДКЛЮЧЕНО",section:"ПРОФИЛЬ И УСТРОЙСТВА",a:"Доступ рядом.",b:"Устройства под контролем.",body:"BetterFy ID для сайта и приложения: вход по никнейму или почте с паролем. Telegram остаётся быстрым отдельным способом.",open:"Открыть профиль"},
    download:{tag:"WINDOWS · РАННИЙ ДОСТУП",a:"BetterFy для",b:"Windows.",body:"Когда публичная тестовая сборка готова, здесь появляются её версия, дата и установщик.",cta:"Скачать BetterFy",check:"Проверить сборку",versions:"Версии на GitHub",title:"BetterFy для Windows",checking:"Проверяем актуальную публичную сборку.",system:"Windows 10/11 · x64",found:"Актуальная версия найдена",login:"Войдите в BetterFy ID",continue:"Войти и продолжить",error:"Не удалось открыть сборку. Попробуйте ещё раз.",version:"ВЕРСИЯ",package:"ФАЙЛ",published:"ОБНОВЛЕНО",locating:"Ищем последнюю сборку…",unavailable:"Публичная сборка ещё не выпущена",network:"Не удалось связаться с GitHub. Проверьте сеть и повторите.",retry:"Повторить"},
    auth:{tag:"BETTERFY ID",title:"Твой BetterFy ID",body:"Войди с паролем или через Telegram.",id:"Войти через BetterFy ID",telegram:"Войти через Telegram",identifier:"Почта или никнейм",username:"Никнейм латиницей",password:"Пароль — от 12 символов",create:"Создать BetterFy ID",forgot:"Забыл пароль? Получить код на почту",registerNote:"Подтверди почту кодом из письма.",email:"Адрес почты",send:"Получить код",emailCode:"Код из письма",emailNote:"Если почта подключена, письмо придёт в течение минуты. Код действует 10 минут.",first:"Для входа с паролем создай BetterFy ID. Telegram — отдельный быстрый вход.",link:"Подключить почту",linked:"Почта подключена",linkNote:"Подтверди адрес, чтобы входить с ним в тот же профиль BetterFy.",back:"Назад",retry:"Попробовать ещё раз",access:"ДОСТУП",notConnected:"Не подключён",sessions:"СЕССИИ",none:"Нет активных",code:"КОД",minutes:"10 минут",get:"Получить код в Telegram",have:"У меня уже есть код",label:"Код подтверждения",enter:"Войти",oneTime:"Код одноразовый и действует 10 минут.",safe:"Профиль под контролем.",safeText:"Способы входа не объединяются автоматически. Активные сеансы можно завершить здесь.",security:"Безопасность",source:"Исходный код",checking:"Проверяем…",invalid:"Проверь данные и попробуй ещё раз.",offline:"Сервис авторизации сейчас недоступен. Ваша локальная сессия сохранена.",storage:"Вход выполнен только для этой вкладки: браузер запретил сохранение сессии.",active:"Активные устройства",until:"до",revoke:"Завершить",signout:"Выйти",early:"Ранний доступ",premium:"Premium"},
    footer:{tag:"Твоя Dota. Только лучше.",product:"ПРОДУКТ",project:"ПРОЕКТ",features:"Возможности",process:"Как работает",telegram:"Telegram",roadmap:"Планы",legal:"Независимый проект. Не связан с Valve Corporation."}
  },
  en: {
    nav:["Features","How it works","Download"], early:"EARLY ACCESS", profile:"Profile", light:"LIGHT", dark:"DARK", open:"OPEN", menu:"Menu", close:"Close", skip:"Skip to content",
    hero:{tag:"DOTA 2 · MOD PLATFORM",a:"Your Dota.",b:"Only better.",body:"Choose mods and cosmetics. BetterFy turns them into one clear plan and surfaces conflicts before confirmation.",cta:"See the app",download:"Check the Windows build",card:"HOME",cardText:"Your active build is always in view"},
    rail:[["SELECT","mods and cosmetics"],["CHECK","files and conflicts"],["BUILD","a ready setup"],["PLAY","launch or restore"]],
    product:{tag:"INSIDE THE APP",a:"Two catalogs.",b:"One build.",body:"Minify handles performance and game tools. Wardrobe covers heroes, HUDs, effects, and audio. They meet only when you build."},
    minify:{tag:"MINIFY · FUNCTIONAL MODS",a:"Tune the game.",b:"Skip the manual work.",body:"Each card explains the mod, shows available previews, and keeps its author and source visible.",items:["Search and seven categories","Author and source stay visible","Conflicts appear before the build"],link:"See the flow"},
    wardrobe:{tag:"WARDROBE · VISUAL MODS",a:"Shape the look",b:"of your game.",body:"Browse 1,135 options for heroes, interface, world, effects, and audio. Your selection stays put while you move between categories.",items:["Search by hero and category","Preview the selected variant","Compatibility and author details"]},
    journey:{tag:"HOW BETTERFY WORKS",a:"From selection",b:"to launch.",body:"Four short steps. At each one, you know what is happening and what comes next.",stage:"STEP",next:"Next step",restart:"Start again"},
    account:{tag:"BETTERFY PROFILE",player:"Player",offline:"Not signed in",setup:"Set up",browser:"This browser",browserState:"Not signed in yet",current:"CURRENT",app:"Windows app",appState:"Connects separately",notConnected:"NOT CONNECTED",section:"PROFILE AND DEVICES",a:"Access stays close.",b:"Devices stay in view.",body:"BetterFy ID for the site and app: use a username or email and password. Telegram remains a separate quick option.",open:"Open profile"},
    download:{tag:"WINDOWS · EARLY ACCESS",a:"BetterFy for",b:"Windows.",body:"When a public test build is ready, its version, date, and installer appear here.",cta:"Download BetterFy",check:"Check the build",versions:"GitHub releases",title:"BetterFy for Windows",checking:"Checking the latest public build.",system:"Windows 10/11 · x64",found:"Latest build found",login:"Sign in to BetterFy ID",continue:"Sign in and continue",error:"The build could not be opened. Please try again.",version:"VERSION",package:"FILE",published:"UPDATED",locating:"Looking for the latest build…",unavailable:"No public build has been released yet",network:"GitHub could not be reached. Check your connection and try again.",retry:"Try again"},
    auth:{tag:"BETTERFY ID",title:"Your BetterFy ID",body:"Use a password or sign in through Telegram.",id:"Sign in with BetterFy ID",telegram:"Sign in with Telegram",identifier:"Email or username",username:"Username",password:"Password — at least 12 characters",create:"Create BetterFy ID",forgot:"Forgot password? Get an email code",registerNote:"Verify your email with the code we send.",email:"Email address",send:"Send a code",emailCode:"Email code",emailNote:"If the email is linked, the message will arrive shortly. The code is valid for 10 minutes.",first:"Create BetterFy ID for password sign-in. Telegram is a separate quick option.",link:"Link an email",linked:"Email linked",linkNote:"Verify an address to sign in to this same BetterFy profile.",back:"Back",retry:"Try again",access:"ACCESS",notConnected:"Not connected",sessions:"SESSIONS",none:"No active sessions",code:"CODE",minutes:"10 minutes",get:"Get a code in Telegram",have:"I already have a code",label:"Confirmation code",enter:"Sign in",oneTime:"The code is single-use and valid for 10 minutes.",safe:"You stay in control.",safeText:"Sign-in methods are not merged automatically. End active sessions here anytime.",security:"Security",source:"Source code",checking:"Checking…",invalid:"Check your details and try again.",offline:"The sign-in service is unavailable. Your local session has been kept.",storage:"Signed in for this tab only because the browser blocked session storage.",active:"Active devices",until:"until",revoke:"End",signout:"Sign out",early:"Early access",premium:"Premium"},
    footer:{tag:"Your Dota. Only better.",product:"PRODUCT",project:"PROJECT",features:"Features",process:"How it works",telegram:"Telegram",roadmap:"Roadmap",legal:"Independent project. Not affiliated with Valve Corporation."}
  }
} as const;

const journeyCopy = {
  ru:[
    {n:"01",title:"Выбрать",label:"12 модов",heading:"Собери свой набор.",text:"Minify и гардероб находятся в отдельных каталогах. У каждого мода есть превью, автор и список изменений.",points:["Фильтры по типу и герою","Превью до добавления","Выбор сохраняется сразу"],icon:Search},
    {n:"02",title:"Проверить",label:"до сборки",heading:"Узнай результат заранее.",text:"BetterFy показывает известные замены, зависимости и конфликты в плане до подтверждения операции.",points:["Состав плана перед глазами","Конфликт рядом с выбором","Понятный итог проверки"],icon:FileCheck2},
    {n:"03",title:"Собрать",label:"по плану",heading:"Подтверди один план.",text:"Фиксированный план связывает выбранный контент с проверяемыми шагами сборки. Production-патчинг пока закрыт до Windows-проверки.",points:["Один итоговый план","Статус каждого шага","Честная граница Early Access"],icon:PackageCheck},
    {n:"04",title:"Восстановить",label:"по журналу",heading:"Сохрани путь назад.",text:"Транзакционная основа использует журнал и отказывается перезаписывать внешние изменения. Реальная Dota-проверка остаётся Windows-гейтом.",points:["Проверка перед действием","Чужие изменения блокируют откат","Синтетические recovery-тесты"],icon:RotateCcw}
  ],
  en:[
    {n:"01",title:"Select",label:"12 mods",heading:"Choose your setup.",text:"Minify and Wardrobe live in separate catalogs. Every mod has a preview, author, and change list.",points:["Filters by type and hero","Preview before adding","Selection saves instantly"],icon:Search},
    {n:"02",title:"Check",label:"before build",heading:"Know the result first.",text:"BetterFy surfaces known replacements, dependencies, and conflicts in the plan before confirmation.",points:["The plan stays visible","Conflicts sit beside choices","A clear check summary"],icon:FileCheck2},
    {n:"03",title:"Build",label:"from one plan",heading:"Confirm one plan.",text:"A fixed plan ties selected content to verifiable build steps. Production patching stays closed until Windows verification.",points:["One final plan","Status for every step","An honest Early Access boundary"],icon:PackageCheck},
    {n:"04",title:"Recover",label:"from the journal",heading:"Keep a way back.",text:"The transaction foundation uses a journal and refuses to overwrite external changes. Real Dota recovery remains a Windows gate.",points:["Check before action","External edits block rollback","Synthetic recovery coverage"],icon:RotateCcw}
  ]
} as const;

const Wordmark=({compact=false}:{compact?:boolean})=><span className={`wordmark ${compact?"compact":""}`} aria-label="BetterFy"><span className="wordmark-better">Better</span><span className="wordmark-fy">Fy</span></span>;

function tiltMove(event:PointerEvent<HTMLElement>){if(window.matchMedia("(prefers-reduced-motion: reduce)").matches||event.pointerType==="touch")return;const node=event.currentTarget,rect=node.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;node.style.setProperty("--tilt-x",`${(.5-y)*8}deg`);node.style.setProperty("--tilt-y",`${(x-.5)*10}deg`);node.style.setProperty("--light-x",`${x*100}%`);node.style.setProperty("--light-y",`${y*100}%`)}
function tiltReset(event:PointerEvent<HTMLElement>){event.currentTarget.style.setProperty("--tilt-x","0deg");event.currentTarget.style.setProperty("--tilt-y","0deg")}
function safeReleaseUrl(value?:string){try{if(!value)return null;const url=new URL(value);return url.protocol==="https:"&&url.hostname==="github.com"&&url.pathname.startsWith("/zori-xyz/BetterFy/releases/")?url.toString():null}catch{return null}}
function openPreview(url:string){window.open(url,"_blank","noopener,noreferrer")}
function readStorage(storage:"local"|"session",key:string){try{return (storage==="local"?localStorage:sessionStorage).getItem(key)}catch{return null}}
function writeSession(key:string,value:string){try{sessionStorage.setItem(key,value);return true}catch{return false}}
function removeSession(key:string){try{sessionStorage.removeItem(key)}catch{}}

function ProfilePanel({language,t,close,stage,session,token,onEmailSignedIn,code,setCode,error,storageWarning,verify,avatar,sessions,revoke,logout}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;stage:AuthStage;session:WebSession|null;token:string|null;onEmailSignedIn:(data:WebSession&{sessionToken:string})=>void;code:string;setCode:(v:string)=>void;error:string;storageWarning:boolean;verify:()=>void;avatar:string|null;sessions:DeviceSession[];revoke:(s:DeviceSession)=>void;logout:()=>void}){
  const access=session?.accessTier==="premium"?t.auth.premium:t.auth.early;
  const[emailMode,setEmailMode]=useState<"choice"|"address"|"code">("choice"),[email,setEmail]=useState(""),[emailCode,setEmailCode]=useState(""),[emailBusy,setEmailBusy]=useState(false),[emailError,setEmailError]=useState(""),[emailIdentity,setEmailIdentity]=useState<{linked:boolean;emailHint:string|null}|null>(null);
  const[idMode,setIdMode]=useState<"choice"|"login"|"register"|"register-code">("choice"),[identifier,setIdentifier]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[idBusy,setIdBusy]=useState(false),[idError,setIdError]=useState("");
  const idRequest=async(path:string,payload:object)=>{const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload),credentials:"omit"});if(!response.ok)throw new Error();return response.json()};
  const submitId=async()=>{setIdBusy(true);setIdError("");try{if(idMode==="register"){await idRequest("/v1/auth/id/register/start",{username,email,password,language});setPassword("");setEmailCode("");setIdMode("register-code");return}const path=idMode==="login"?"/v1/auth/id/login":"/v1/auth/id/register/verify";const data=await idRequest(path,idMode==="login"?{identifier,password,clientKind:"web"}:{email,code:emailCode,clientKind:"web"});if(!data.sessionToken||!data.displayName)throw new Error();setPassword("");onEmailSignedIn(data);setIdMode("choice")}catch{setIdError(t.auth.invalid)}finally{setIdBusy(false)}};
  useEffect(()=>{if(!token)return;const controller=new AbortController();fetch(new URL("/v1/session/email",authUrl),{headers:{Authorization:`Bearer ${token}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(data=>setEmailIdentity(data)).catch(()=>{});return()=>controller.abort()},[token]);
  const startEmail=async()=>{setEmailBusy(true);setEmailError("");try{const path=session?"/v1/session/email/start":"/v1/auth/email/start";const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json",...(session&&token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({email,language}),credentials:"omit"});if(!response.ok)throw new Error();setEmailMode("code");setEmailCode("")}catch{setEmailError(t.auth.offline)}finally{setEmailBusy(false)}};
  const verifyEmail=async()=>{setEmailBusy(true);setEmailError("");try{const path=session?"/v1/session/email/verify":"/v1/auth/email/verify";const response=await fetch(new URL(path,authUrl),{method:"POST",headers:{"content-type":"application/json",...(session&&token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({email,code:emailCode,...(!session?{clientKind:"web"}:{})}),credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json();if(session){setEmailIdentity({linked:true,emailHint:data.emailHint});setEmailMode("choice")}else if(data.sessionToken&&data.displayName){onEmailSignedIn(data);setEmailMode("choice")}else throw new Error()}catch{setEmailError(t.auth.invalid)}finally{setEmailBusy(false)}};
  return <div className="modal-backdrop" onMouseDown={close}><section className="profile-panel" role="dialog" aria-modal="true" aria-labelledby="profile-title" onMouseDown={e=>e.stopPropagation()}>
    <button className="modal-close" onClick={close} aria-label={t.close}><X size={17}/></button>
    <div className="profile-head"><div className="profile-avatar">{avatar?<img src={avatar} alt=""/>:<UserRound size={34}/>}<span>BF</span></div><div><p className="micro">{t.auth.tag}</p><h2 id="profile-title">{session?session.displayName:t.auth.title}</h2><p>{session?(session.username?`@${session.username} · ${access}`:access):t.auth.body}</p></div></div>
    {storageWarning&&<p className="status-note warning" role="status"><AlertTriangle size={16}/>{t.auth.storage}</p>}
    {stage==="unavailable"&&!session&&<p className="status-note error" role="alert"><WifiOff size={16}/>{t.auth.offline}</p>}
    {!session&&idMode!=="choice"&&<form className="site-id-form" onSubmit={e=>{e.preventDefault();void submitId()}}><button className="site-id-back" type="button" onClick={()=>{setIdMode("choice");setIdError("")}}>{t.auth.back}</button><h3>{idMode==="login"?t.auth.id:idMode==="register"?t.auth.create:t.auth.emailCode}</h3>{idMode==="register"&&<p>{t.auth.registerNote}</p>}{idMode==="login"&&<input aria-label={t.auth.identifier} autoComplete="username" required maxLength={254} placeholder={t.auth.identifier} value={identifier} onChange={e=>setIdentifier(e.target.value)}/ >}{idMode==="register"&&<><input aria-label={t.auth.username} autoComplete="username" required minLength={3} maxLength={24} pattern="[A-Za-z][A-Za-z0-9_]{2,23}" placeholder={t.auth.username} value={username} onChange={e=>setUsername(e.target.value)}/><input aria-label={t.auth.email} type="email" autoComplete="email" required maxLength={254} placeholder={t.auth.email} value={email} onChange={e=>setEmail(e.target.value)}/></>}{(idMode==="login"||idMode==="register")&&<input aria-label={t.auth.password} type="password" autoComplete={idMode==="register"?"new-password":"current-password"} required minLength={12} maxLength={128} placeholder={t.auth.password} value={password} onChange={e=>setPassword(e.target.value)}/ >}{idMode==="register-code"&&<><p>{t.auth.registerNote}</p><input aria-label={t.auth.emailCode} inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength={6} value={emailCode} onChange={e=>setEmailCode(e.target.value.replace(/\D/g,"").slice(0,6))}/></>}{idError&&<small role="alert" className="is-error">{idError}</small>}<button className="site-id-primary" disabled={idBusy||(idMode==="register-code"&&emailCode.length!==6)}>{idBusy?t.auth.checking:idMode==="login"?t.auth.enter:idMode==="register"?t.auth.create:t.auth.emailCode}<ArrowRight size={16}/></button>{idMode==="login"&&<><button className="site-id-back" type="button" onClick={()=>setIdMode("register")}>{t.auth.create}</button><button className="site-id-back" type="button" onClick={()=>{setEmail(identifier.includes("@")?identifier:"");setIdMode("choice");setEmailMode("address")}}>{t.auth.forgot}</button></>}</form>}
    {idMode==="choice"&&emailMode!=="choice"&&<form className="site-id-form" onSubmit={e=>{e.preventDefault();void(emailMode==="address"?startEmail():verifyEmail())}}><button className="site-id-back" type="button" onClick={()=>{setEmailMode("choice");setEmailError("")}}>{t.auth.back}</button><h3>{emailMode==="address"?t.auth.email:t.auth.emailCode}</h3><p>{emailMode==="address"?session?t.auth.linkNote:t.auth.first:t.auth.emailNote}</p>{emailMode==="address"?<input aria-label={t.auth.email} type="email" autoComplete="email" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/>:<input aria-label={t.auth.emailCode} type="text" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={emailCode} onChange={e=>setEmailCode(e.target.value.replace(/\D/g,"").slice(0,6))}/ >}{emailError&&<small role="alert" className="is-error">{emailError}</small>}<button className="site-id-primary" disabled={emailBusy||(emailMode==="code"&&emailCode.length!==6)}>{emailBusy?t.auth.checking:emailMode==="address"?t.auth.send:t.auth.enter}<ArrowRight size={16}/></button>{emailMode==="code"&&<button className="site-id-back" type="button" disabled={emailBusy} onClick={()=>void startEmail()}>{t.auth.retry}</button>}</form>}
    {idMode==="choice"&&emailMode==="choice"&&(session?<>
      <div className="profile-summary"><div><ShieldCheck size={18}/><span>{t.auth.access}</span><strong>{access}</strong></div><div><Monitor size={18}/><span>{t.auth.sessions}</span><strong>{sessions.length}</strong></div><div><KeyRound size={18}/><span>ID</span><strong>{session.userId.slice(0,8)}</strong></div></div>
      <div className="site-id-link"><span className="site-id-icon"><Mail size={20}/></span><div><b>{language==="ru"?"Почта для входа по коду":"Email code sign-in"}</b><small>{emailIdentity?.linked?`${t.auth.linked} · ${emailIdentity.emailHint}`:t.auth.linkNote}</small></div>{!emailIdentity?.linked&&emailMode==="choice"&&<button type="button" onClick={()=>setEmailMode("address")}>{t.auth.link}<ArrowRight size={15}/></button>}</div>
      <div className="device-list"><h3>{t.auth.active}</h3>{sessions.map(item=><article key={item.sessionId}><span className="device-icon">{item.clientKind==="desktop"?<Gamepad2 size={17}/>:<Monitor size={17}/>}</span><div><b>{item.clientKind==="desktop"?"BetterFy Windows":language==="ru"?"Веб-сайт BetterFy":"BetterFy website"}</b><small>{t.auth.until} {new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(item.expiresAt*1000))}</small></div>{item.current?<em>{t.account.current}</em>:<button onClick={()=>revoke(item)}>{t.auth.revoke}</button>}</article>)}</div>
      <button className="signout-button" onClick={logout}><LogOut size={15}/>{t.auth.signout}</button>
    </>:<>
      {emailMode==="choice"&&<div className="site-id-choices"><button className="site-id-primary" type="button" onClick={()=>setIdMode("login")}><KeyRound size={18}/><b>{t.auth.id}</b><ArrowRight size={17}/></button><a className="site-id-telegram" href={bot} target="_blank" rel="noreferrer" onClick={()=>setCode("")}><Send size={18}/><b>{t.auth.telegram}</b><ExternalLink size={16}/></a><p>{t.auth.first}</p></div>}
      {emailMode==="choice"&&stage==="idle"&&<button className="have-code-button" type="button" onClick={()=>setCode("")}><KeyRound size={14}/>{t.auth.have}</button>}
      {(stage==="code"||stage==="verifying")&&<form className="code-row otp-form" onSubmit={e=>{e.preventDefault();verify()}}><label htmlFor="access-code">{t.auth.label}</label><div className="code-entry"><div className="otp-control"><div className="otp-slots" aria-hidden="true">{Array.from({length:6},(_,index)=><span key={index} className={code.length===index?"current":""}>{code[index]||""}</span>)}</div><input className="otp-input" id="access-code" aria-label={t.auth.label} inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} disabled={stage==="verifying"}/></div><button className="otp-submit" type="submit" disabled={stage==="verifying"||code.length!==6}>{stage==="verifying"?t.auth.checking:t.auth.enter}<ArrowRight size={15}/></button></div><small className={error?"is-error":""}>{error||t.auth.oneTime}</small></form>}
      <div className="profile-note"><ShieldCheck size={16}/><p><b>{t.auth.safe}</b><span>{t.auth.safeText}</span></p></div>
    </>)}
    <div className="profile-links"><a href={`${repo}/blob/main/docs/IDENTITY_AND_WEB_ARCHITECTURE.md`}>{t.auth.security}<ExternalLink size={12}/></a><a href={repo}>{t.auth.source}<ExternalLink size={12}/></a></div>
  </section></div>
}

function DownloadPanel({language,t,close,session,release,releaseState,retry,openProfile,download,error}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;session:WebSession|null;release:ReleaseMeta|null;releaseState:ReleaseState;retry:()=>void;openProfile:()=>void;download:()=>void;error:string}){
  const date=release?new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(release.publishedAt)):"-";
  const size=release?`${(release.size/1048576).toFixed(1)} MB`:"-";
  const loading=releaseState==="loading";
  return <div className="modal-backdrop" onMouseDown={close}><section className="download-panel" role="dialog" aria-modal="true" aria-labelledby="download-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close} aria-label={t.close}><X size={17}/></button><div className="download-mark"><Wordmark/></div><p className="micro">WINDOWS · EARLY ACCESS</p><h2 id="download-title">{t.download.title}</h2><p>{t.download.checking}</p><div className="download-checks"><span className="active"><i><Check size={14}/></i>{t.download.system}</span><span className={release?"active":releaseState==="unavailable"?"error":""}><i>{release?<Check size={14}/>:releaseState==="unavailable"?<WifiOff size={14}/>:"2"}</i>{loading?t.download.locating:release?t.download.found:releaseState==="unavailable"?t.download.network:t.download.unavailable}</span><span className={session?"active":""}><i>{session?<Check size={14}/>:"3"}</i>{session?session.displayName:t.download.login}</span></div>{release&&<div className="release-details"><span><small>{t.download.version}</small><b>{release.version}</b></span><span><small>{t.download.package}</small><b title={release.fileName}>{size}</b></span><span><small>{t.download.published}</small><b>{date}</b></span></div>}{releaseState==="unavailable"&&<button className="retry-button" onClick={retry}>{t.download.retry}</button>}<button className="action primary wide" onClick={session?download:openProfile} disabled={loading||(!release&&Boolean(session))}><span className="action-icon">{session?<ArrowDownToLine size={17}/>:<CircleUserRound size={17}/>}</span><b>{session?t.download.cta:t.download.continue}</b><ArrowRight size={17}/></button>{error&&<p className="download-error" role="alert">{error}</p>}<a className="quiet-link" href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></section></div>
}

export default function Site(){
  const[language,setLanguage]=useState<Language>("ru"),[profile,setProfile]=useState(false),[download,setDownload]=useState(false),[mobileMenu,setMobileMenu]=useState(false),[active,setActive]=useState(0),[darkWardrobe,setDarkWardrobe]=useState(false);
  const[authStage,setAuthStage]=useState<AuthStage>("checking"),[authSession,setAuthSession]=useState<WebSession|null>(null),[sessionToken,setSessionToken]=useState<string|null>(null),[authCode,setAuthCode]=useState(""),[authError,setAuthError]=useState(""),[storageWarning,setStorageWarning]=useState(false),[avatarUrl,setAvatarUrl]=useState<string|null>(null),[deviceSessions,setDeviceSessions]=useState<DeviceSession[]>([]),[downloadError,setDownloadError]=useState(""),[releaseMeta,setReleaseMeta]=useState<ReleaseMeta|null>(null),[releaseState,setReleaseState]=useState<ReleaseState>("idle"),[releaseAttempt,setReleaseAttempt]=useState(0);
  const returnFocus=useRef<HTMLElement|null>(null);
  const t=copy[language],steps=journeyCopy[language],step=useMemo(()=>steps[active],[steps,active]),StepIcon=step.icon;
  const modalOpen=profile||download;
  const wardrobeImage=asset(language==="en"?(darkWardrobe?"poster-wardrobe-en-dark.webp":"poster-wardrobe-en-light.webp"):(darkWardrobe?"poster-wardrobe-ru-dark.webp":"poster-wardrobe.webp"));
  const minifyImage=asset(language==="en"?"poster-minify-en.webp":"poster-minify.webp");
  const homeImage=asset(language==="en"?"app-home-dark-en.webp":"app-home-original.webp");

  useEffect(()=>{const saved=readStorage("local","betterfy-site-language");if(saved==="en")setLanguage("en");const stored=readStorage("session",sessionKey);if(stored)setSessionToken(stored);else setAuthStage("idle")},[]);
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem("betterfy-site-language",language)}catch{}},[language]);
  useEffect(()=>{if(!modalOpen)return;returnFocus.current=document.activeElement instanceof HTMLElement?document.activeElement:null;const background=[document.querySelector<HTMLElement>(".site-header"),document.querySelector<HTMLElement>("main")].filter((node):node is HTMLElement=>Boolean(node));background.forEach(node=>{node.inert=true;node.setAttribute("aria-hidden","true")});document.body.style.overflow="hidden";const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setProfile(false);setDownload(false);return}if(event.key!=="Tab")return;const dialog=document.querySelector<HTMLElement>('[role="dialog"]');if(!dialog)return;const focusable=Array.from(dialog.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')).filter(node=>node.offsetParent!==null);if(focusable.length===0){event.preventDefault();dialog.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};window.addEventListener("keydown",onKey);return()=>{window.removeEventListener("keydown",onKey);background.forEach(node=>{node.inert=false;node.removeAttribute("aria-hidden")});document.body.style.overflow="";returnFocus.current?.focus();returnFocus.current=null}},[modalOpen]);
  useEffect(()=>{if(!modalOpen)return;const frame=requestAnimationFrame(()=>document.querySelector<HTMLElement>('[role="dialog"] .modal-close')?.focus());return()=>cancelAnimationFrame(frame)},[modalOpen,profile,download]);
  useEffect(()=>{if(!mobileMenu)return;const closeMenu=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();setMobileMenu(false);requestAnimationFrame(()=>document.querySelector<HTMLElement>(".menu-button")?.focus())}};window.addEventListener("keydown",closeMenu);return()=>window.removeEventListener("keydown",closeMenu)},[mobileMenu]);
  useEffect(()=>{const nodes=Array.from(document.querySelectorAll<HTMLElement>(".reveal"));if(matchMedia("(prefers-reduced-motion: reduce)").matches||!("IntersectionObserver" in window)){nodes.forEach(n=>n.classList.add("is-visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:"0px 0px -7%"});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);
  useEffect(()=>{if(!sessionToken){setAuthSession(null);setAuthStage("idle");return}const controller=new AbortController();setAuthStage("checking");fetch(new URL("/v1/session/profile",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(async response=>{if(response.status===401||response.status===403){removeSession(sessionKey);setSessionToken(null);setAuthSession(null);setAuthStage("idle");return null}if(!response.ok)throw new Error("profile_unavailable");return response.json() as Promise<WebSession>}).then(data=>{if(!data)return;setAuthSession(data);setAuthStage("ready")}).catch(e=>{if(e instanceof DOMException&&e.name==="AbortError")return;setAuthStage("unavailable")});return()=>controller.abort()},[sessionToken]);
  useEffect(()=>{if(!sessionToken||!authSession?.avatarAvailable){setAvatarUrl(null);return}const controller=new AbortController();let objectUrl:string|null=null;fetch(new URL("/v1/session/avatar",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.blob():Promise.reject()).then(blob=>{objectUrl=URL.createObjectURL(blob);setAvatarUrl(objectUrl)}).catch(()=>setAvatarUrl(null));return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[sessionToken,authSession?.avatarAvailable]);
  useEffect(()=>{if(!profile||!sessionToken||!authSession)return;const controller=new AbortController();fetch(new URL("/v1/session/devices",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then((data:{sessions?:DeviceSession[]})=>setDeviceSessions(Array.isArray(data.sessions)?data.sessions:[])).catch(()=>setDeviceSessions([]));return()=>controller.abort()},[profile,sessionToken,authSession]);
  useEffect(()=>{if(!download)return;const controller=new AbortController();setReleaseState("loading");fetch("https://api.github.com/repos/zori-xyz/BetterFy/releases/latest",{headers:{Accept:"application/vnd.github+json"},signal:controller.signal}).then(async response=>{if(response.status===404){setReleaseState("missing");return null}if(!response.ok)throw new Error("release_unavailable");return response.json() as Promise<{tag_name?:string;published_at?:string;assets?:Array<{name?:string;size?:number}>}>}).then(data=>{if(!data)return;const installer=data.assets?.find(item=>/\.(exe|msi)$/i.test(item.name||""));if(!data.tag_name||!data.published_at||!installer?.name||!installer.size){setReleaseState("missing");return}setReleaseMeta({version:data.tag_name,fileName:installer.name,size:installer.size,publishedAt:data.published_at});setReleaseState("ready")}).catch(()=>{if(!controller.signal.aborted)setReleaseState("unavailable")});return()=>controller.abort()},[download,releaseAttempt]);

  const verifyCode=async()=>{if(!/^\d{6}$/.test(authCode)){setAuthError(t.auth.invalid);return}setAuthStage("verifying");setAuthError("");try{const response=await fetch(new URL("/v1/auth/telegram/code",authUrl),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:authCode,clientKind:"web"}),credentials:"omit"});if(!response.ok)throw new Error("invalid_code");const data=await response.json() as WebSession&{sessionToken?:string};if(!data.sessionToken||!data.displayName)throw new Error("invalid_response");setStorageWarning(!writeSession(sessionKey,data.sessionToken));setSessionToken(data.sessionToken);setAuthSession(data);setAuthStage("ready");setAuthCode("")}catch(error){setAuthStage("code");setAuthError(error instanceof TypeError?t.auth.offline:t.auth.invalid)}};
  const revoke=async(item:DeviceSession)=>{if(!sessionToken)return;try{const response=await fetch(new URL("/v1/session/devices/revoke",authUrl),{method:"POST",headers:{Authorization:`Bearer ${sessionToken}`,"content-type":"application/json"},body:JSON.stringify({sessionId:item.sessionId}),credentials:"omit"});if(!response.ok)throw new Error();if(item.current){logout();return}setDeviceSessions(v=>v.filter(x=>x.sessionId!==item.sessionId))}catch{}};
  const logout=()=>{const token=sessionToken;removeSession(sessionKey);setStorageWarning(false);setSessionToken(null);setAuthSession(null);setAvatarUrl(null);setDeviceSessions([]);setAuthStage("idle");if(token)fetch(new URL("/v1/session/logout",authUrl),{method:"POST",headers:{Authorization:`Bearer ${token}`},credentials:"omit"}).catch(()=>undefined)};
  const downloadBuild=async()=>{setDownloadError("");if(!sessionToken||!authSession){setDownload(false);setProfile(true);return}try{const response=await fetch(new URL("/v1/releases/latest",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json() as{downloadUrl?:string};const url=safeReleaseUrl(data.downloadUrl);if(!url)throw new Error();window.location.assign(url)}catch{setDownloadError(t.download.error)}};

  const closeMobileMenu=()=>setMobileMenu(false);
  return <><a className="skip-link" href="#content">{t.skip}</a><header className="site-header"><a href="#top" aria-label="BetterFy"><Wordmark compact/></a><nav aria-label={t.menu}><a href="#product">{t.nav[0]}</a><a href="#journey">{t.nav[1]}</a><a href="#download">{t.nav[2]}</a></nav><div className="header-actions"><div className="language-switch" role="group" aria-label={language==="ru"?"Язык":"Language"}><button aria-pressed={language==="ru"} className={language==="ru"?"active":""} onClick={()=>setLanguage("ru")}>RU</button><button aria-pressed={language==="en"} className={language==="en"?"active":""} onClick={()=>setLanguage("en")}>EN</button></div><span className="live"><i/>{t.early}</span><button className="profile-button" onClick={()=>setProfile(true)}>{avatarUrl?<img src={avatarUrl} alt=""/>:<CircleUserRound size={16}/>} <span>{authSession?.displayName||t.profile}</span></button><button className="menu-button" type="button" aria-label={mobileMenu?t.close:t.menu} aria-expanded={mobileMenu} aria-controls="mobile-navigation" onClick={()=>setMobileMenu(value=>!value)}>{mobileMenu?<X size={19}/>:<Menu size={19}/>}</button></div>{mobileMenu&&<nav className="mobile-navigation" id="mobile-navigation" aria-label={t.menu}><a href="#product" onClick={closeMobileMenu}>{t.nav[0]}</a><a href="#journey" onClick={closeMobileMenu}>{t.nav[1]}</a><a href="#download" onClick={closeMobileMenu}>{t.nav[2]}</a><button onClick={()=>{closeMobileMenu();setProfile(true)}}>{t.profile}</button></nav>}</header>
  <main id="content"><section id="top" className="hero shell"><div className="hero-copy"><p className="eyebrow"><Sparkles size={13}/>{t.hero.tag}</p><h1>{t.hero.a}<br/><strong>{t.hero.b}</strong></h1><p className="lead">{t.hero.body}</p><div className="hero-actions"><button className="action primary" onClick={()=>document.querySelector("#product")?.scrollIntoView({behavior:"smooth"})}><span className="action-icon"><Layers3 size={18}/></span><b>{t.hero.cta}</b><ArrowRight size={18}/></button><button className="text-action" onClick={()=>setDownload(true)}>{t.hero.download}<Download size={15}/></button></div></div><figure className="hero-poster tilt-card app-screen" onPointerMove={tiltMove} onPointerLeave={tiltReset}><div className="poster-glow"/><img src={homeImage} width="1195" height="758" alt={language==="ru"?"Главный экран BetterFy с активной сборкой":"BetterFy home with the active build"}/><figcaption><span>{t.hero.card}</span><b>{t.hero.cardText}</b></figcaption></figure></section>
  <section className="state-rail shell reveal" aria-label={language==="ru"?"Путь сборки":"Build flow"}>{t.rail.map((item,i)=><Fragment key={item[0]}><div><span>{String(i+1).padStart(2,"0")}</span><b>{item[0]}</b><small>{item[1]}</small></div>{i<3&&<i/>}</Fragment>)}</section>
  <section className="product shell" id="product"><div className="section-intro reveal"><p className="eyebrow">{t.product.tag}</p><h2>{t.product.a}<br/><strong>{t.product.b}</strong></h2><p>{t.product.body}</p></div><article className="feature dark-feature reveal"><div className="feature-copy"><p className="micro">{t.minify.tag}</p><h3>{t.minify.a}<br/>{t.minify.b}</h3><p>{t.minify.body}</p><ul>{t.minify.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><a href="#journey">{t.minify.link}<ChevronRight size={14}/></a></div><button className="poster-button tilt-card" onPointerMove={tiltMove} onPointerLeave={tiltReset} onClick={()=>openPreview(minifyImage)} aria-label={language==="ru"?"Открыть экран каталога Minify":"Open the Minify catalog screen"}><img key={minifyImage} src={minifyImage} width="1716" height="917" loading="lazy" alt={language==="ru"?"Каталог функциональных модов Minify в BetterFy":"BetterFy functional Minify mod catalog"}/><span>{t.open}<ExternalLink size={12}/></span></button></article>
  <article className={`feature light-feature reveal is-visible ${darkWardrobe?"is-dark-preview":""}`}><button className="poster-button tilt-card wardrobe-screen" onPointerMove={tiltMove} onPointerLeave={tiltReset} onClick={()=>openPreview(wardrobeImage)} aria-label={language==="ru"?"Открыть экран гардероба":"Open the Wardrobe screen"}><img key={wardrobeImage} src={wardrobeImage} width="1536" height="1024" loading="lazy" alt={language==="ru"?"Визуальный каталог гардероба BetterFy":"BetterFy visual Wardrobe catalog"}/><span>{t.open}<ExternalLink size={12}/></span></button><div className="feature-copy"><div className="theme-switch" role="group" aria-label={language==="ru"?"Тема превью":"Preview theme"}><button type="button" aria-pressed={!darkWardrobe} className={!darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(false)}>{t.light}</button><button type="button" aria-pressed={darkWardrobe} className={darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(true)}>{t.dark}</button></div><p className="micro">{t.wardrobe.tag}</p><h3>{t.wardrobe.a}<br/>{t.wardrobe.b}</h3><p>{t.wardrobe.body}</p><ul>{t.wardrobe.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></article></section>
  <section className="journey" id="journey"><div className="shell"><div className="journey-intro reveal"><p className="eyebrow">{t.journey.tag}</p><h2>{t.journey.a}<br/><strong>{t.journey.b}</strong></h2><p>{t.journey.body}</p></div><div className="journey-board reveal"><div className="journey-tabs" role="tablist" aria-label={t.journey.tag} onKeyDown={event=>{const keys=["ArrowRight","ArrowDown","ArrowLeft","ArrowUp","Home","End"];if(!keys.includes(event.key))return;event.preventDefault();const next=event.key==="Home"?0:event.key==="End"?steps.length-1:event.key==="ArrowRight"||event.key==="ArrowDown"?(active+1)%steps.length:(active-1+steps.length)%steps.length;setActive(next);requestAnimationFrame(()=>document.getElementById(`journey-tab-${next}`)?.focus())}}>{steps.map((item,i)=>{const Icon=item.icon;return <button id={`journey-tab-${i}`} key={item.n} role="tab" aria-selected={active===i} aria-controls="journey-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)}><i><Icon size={18}/></i><b>{item.title}</b><small>{item.label}</small></button>})}</div><div id="journey-panel" role="tabpanel" aria-labelledby={`journey-tab-${active}`} tabIndex={0} className="journey-detail" key={`${language}-${step.n}`}><div className="stage-visual"><div className="stage-logo"><Wordmark compact/></div><StepIcon size={54}/><span>{step.title}</span></div><div className="stage-copy"><p className="micro">{step.title}</p><h3>{step.heading}</h3><p>{step.text}</p><ul>{step.points.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><button onClick={()=>setActive(active===3?0:active+1)}>{active===3?t.journey.restart:t.journey.next}<ArrowRight size={16}/></button></div></div><div className="journey-progress" aria-hidden="true"><i style={{width:`${25*(active+1)}%`}}/></div></div></div></section>
  <section className="account shell reveal"><div className="account-visual"><div className="account-card"><div className="account-avatar">{avatarUrl?<img src={avatarUrl} alt=""/>:<UserRound size={27}/>}</div><div><p className="micro">{t.account.tag}</p><h3>{authSession?.displayName||t.account.player}</h3><span>{authSession?(authSession.username?`@${authSession.username}`:t.auth.early):t.account.offline}</span></div><button onClick={()=>setProfile(true)}>{t.account.setup}<ArrowRight size={14}/></button></div><div className="session-row"><Monitor size={17}/><div><b>{t.account.browser}</b><span>{authSession?t.auth.safe:t.account.browserState}</span></div><em>{t.account.current}</em></div><div className="session-row"><Gamepad2 size={17}/><div><b>{t.account.app}</b><span>{t.account.appState}</span></div><em>{t.account.notConnected}</em></div></div><div className="account-copy"><p className="eyebrow">{t.account.section}</p><h2>{t.account.a}<br/><strong>{t.account.b}</strong></h2><p>{t.account.body}</p><button className="action secondary" onClick={()=>setProfile(true)}><span className="action-icon"><CircleUserRound size={18}/></span><b>{t.account.open}</b><ArrowRight size={18}/></button></div></section>
  <section className="download-section" id="download"><div className="download-aura"/><div className="shell download-inner reveal"><div><p className="eyebrow">{t.download.tag}</p><h2>{t.download.a}<br/><strong>{t.download.b}</strong></h2><p>{t.download.body}</p></div><div className="download-cta"><button className="action primary huge" onClick={()=>setDownload(true)}><span className="action-icon"><ArrowDownToLine size={19}/></span><b>{releaseMeta?t.download.cta:t.download.check}</b><ArrowRight size={19}/></button><span>{t.download.system}</span><a href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></div></div></section>
  <footer className="site-footer shell"><div><Wordmark/><p>{t.footer.tag}</p></div><div><b>{t.footer.product}</b><a href="#product">{t.footer.features}</a><a href="#journey">{t.footer.process}</a><button onClick={()=>setProfile(true)}>{t.profile}</button></div><div><b>{t.footer.project}</b><a href={repo}>GitHub<ExternalLink size={11}/></a><a href={bot}>{t.footer.telegram}<ExternalLink size={11}/></a><a href={`${repo}/blob/main/docs/ROADMAP.md`}>{t.footer.roadmap}<ExternalLink size={11}/></a></div><span>{t.footer.legal}</span></footer></main>
  {profile&&<ProfilePanel language={language} t={t} close={()=>setProfile(false)} stage={authStage} session={authSession} token={sessionToken} onEmailSignedIn={data=>{setStorageWarning(!writeSession(sessionKey,data.sessionToken));setSessionToken(data.sessionToken);setAuthSession(data);setAuthStage("ready")}} code={authCode} setCode={v=>{setAuthCode(v);setAuthError("");setAuthStage("code")}} error={authError} storageWarning={storageWarning} verify={verifyCode} avatar={avatarUrl} sessions={deviceSessions} revoke={revoke} logout={logout}/>} {download&&<DownloadPanel language={language} t={t} close={()=>setDownload(false)} session={authSession} release={releaseMeta} releaseState={releaseState} retry={()=>{setReleaseMeta(null);setReleaseAttempt(value=>value+1)}} openProfile={()=>{setDownload(false);setProfile(true)}} download={downloadBuild} error={downloadError}/>}</>;
}
