import { Fragment, useEffect, useMemo, useState, type PointerEvent } from "react";
import { ArrowDownToLine, ArrowRight, Check, ChevronRight, CircleUserRound, Download, ExternalLink, FileCheck2, Gamepad2, KeyRound, Layers3, LogOut, Monitor, PackageCheck, RotateCcw, Search, Send, ShieldCheck, Sparkles, UserRound, X } from "lucide-react";

type Language = "ru" | "en";
type AuthStage = "idle" | "checking" | "code" | "verifying" | "ready";
type WebSession = { userId:string; displayName:string; username?:string; accessTier:string; accessExpiresAt?:number; sessionId?:string; avatarAvailable:boolean };
type DeviceSession = { sessionId:string; clientKind:"web"|"desktop"|"unknown"; lastUsedAt:number; expiresAt:number; current:boolean };
type ReleaseMeta = { version:string; fileName:string; size:number; publishedAt:string };

const repo = "https://github.com/zori-xyz/BetterFy";
const bot = "https://t.me/BeterFyBot?start=web_login";
const authUrl = import.meta.env.VITE_BETTERFY_AUTH_URL || "https://betterfy-auth.zori-xyz.workers.dev";
const sessionKey = "betterfy:web-session";
const asset = (name:string) => `${import.meta.env.BASE_URL}${name}`;

const copy = {
  ru: {
    nav:["Возможности","Как работает","Скачать"], early:"РАННИЙ ДОСТУП", profile:"Профиль", light:"СВЕТЛАЯ", dark:"ТЁМНАЯ", open:"ОТКРЫТЬ",
    hero:{tag:"DOTA 2 · ПЛАТФОРМА МОДОВ",a:"Твоя Dota.",b:"Только лучше.",body:"Выбирайте моды и оформление в одном приложении. BetterFy проверит сборку до установки и сохранит возможность отката.",cta:"Посмотреть приложение",download:"Скачать для Windows",trust:"Dota 2 определяется автоматически",open:"Открытый код · GPL-3.0",card:"ГЛАВНАЯ",cardText:"Активная сборка всегда перед глазами"},
    rail:[["ВЫБОР","моды и оформление"],["ПРОВЕРКА","файлы и конфликты"],["СБОРКА","готовый набор"],["ЗАПУСК","игра или откат"]],
    product:{tag:"ВНУТРИ ПРИЛОЖЕНИЯ",a:"Два каталога.",b:"Одна сборка.",body:"Minify отвечает за оптимизацию и игровые инструменты. Гардероб — за героев, HUD, эффекты и звук. Выбранное объединяется только на этапе сборки."},
    minify:{tag:"MINIFY · ФУНКЦИОНАЛЬНЫЕ МОДЫ",a:"Убери лишнее.",b:"Оставь игру.",body:"У каждого мода есть сравнение до и после, описание и точный список ресурсов, которые он меняет.",items:["Поиск и семь категорий","Автор и источник на месте","Конфликт виден до установки"],link:"Посмотреть процесс"},
    wardrobe:{tag:"ГАРДЕРОБ · ВИЗУАЛЬНЫЕ МОДЫ",a:"Настрой внешний",b:"вид игры.",body:"В каталоге 1 135 вариантов для героев, интерфейса, мира, эффектов и звука. Выбор остаётся на месте при переходе между категориями.",items:["Поиск по герою и категории","Превью выбранного варианта","Совместимость и автор"]},
    journey:{tag:"КАК РАБОТАЕТ BETTERFY",a:"От выбора",b:"до запуска.",body:"Четыре коротких шага. На каждом видно, что происходит со сборкой и что делать дальше.",stage:"ЭТАП",next:"Следующий этап",restart:"Начать сначала"},
    account:{tag:"ПРОФИЛЬ BETTERFY",player:"Игрок",offline:"Telegram не подключён",setup:"Настроить",browser:"Этот браузер",browserState:"Вход ещё не выполнен",current:"ТЕКУЩИЙ",app:"Приложение Windows",appState:"Ожидает подтверждения",notConnected:"НЕ ПОДКЛЮЧЕНО",section:"ПРОФИЛЬ И УСТРОЙСТВА",a:"Сборки рядом.",b:"Доступ под контролем.",body:"Профиль хранит ваши сборки и список подключённых устройств. Вход подтверждается одноразовым кодом через Telegram.",open:"Открыть профиль"},
    download:{tag:"WINDOWS · РАННИЙ ДОСТУП",a:"Попробуй BetterFy",b:"на своей Dota.",body:"Тестовая версия доступна для Windows 10 и 11. Для загрузки понадобится профиль BetterFy.",cta:"Скачать BetterFy",versions:"Версии на GitHub",title:"Скачать BetterFy",checking:"Проверяем платформу и актуальную тестовую сборку.",system:"Windows 10/11 · x64",found:"Актуальная версия найдена",login:"Войдите через Telegram",continue:"Войти и продолжить",error:"Не удалось открыть сборку. Попробуйте ещё раз.",version:"ВЕРСИЯ",package:"ФАЙЛ",published:"ОБНОВЛЕНО",locating:"Ищем последнюю сборку…",unavailable:"Публичная сборка ещё не выпущена"},
    auth:{tag:"ПРОФИЛЬ BETTERFY",title:"Вход в аккаунт",body:"Получите код в Telegram и введите его здесь. BetterFy не запрашивает доступ к перепискам.",access:"ДОСТУП",notConnected:"Не подключён",sessions:"СЕССИИ",none:"Нет активных",code:"КОД",minutes:"10 минут",get:"Получить код в Telegram",have:"У меня уже есть код",label:"Код подтверждения",enter:"Войти",oneTime:"Код одноразовый и действует 10 минут.",safe:"Всё под контролем.",safeText:"Новые устройства подтверждаются отдельно, а любую сессию можно завершить в профиле.",security:"Безопасность",source:"Исходный код",checking:"Проверяем…",invalid:"Код не подошёл или уже использован.",active:"Активные устройства",until:"до",revoke:"Завершить",signout:"Выйти",early:"Ранний доступ",premium:"Premium"},
    footer:{tag:"Твоя Dota. Только лучше.",product:"ПРОДУКТ",project:"ПРОЕКТ",features:"Возможности",process:"Как работает",telegram:"Telegram",roadmap:"Планы",legal:"Независимый проект. Не связан с Valve Corporation."}
  },
  en: {
    nav:["Features","How it works","Download"], early:"EARLY ACCESS", profile:"Profile", light:"LIGHT", dark:"DARK", open:"OPEN",
    hero:{tag:"DOTA 2 · MOD PLATFORM",a:"Your Dota.",b:"Only better.",body:"Choose mods and cosmetics in one app. BetterFy checks the build before installation and keeps a safe way back.",cta:"See the app",download:"Download for Windows",trust:"Dota 2 is detected automatically",open:"Open source · GPL-3.0",card:"HOME",cardText:"Your active build is always in view"},
    rail:[["SELECT","mods and cosmetics"],["CHECK","files and conflicts"],["BUILD","a ready setup"],["PLAY","launch or restore"]],
    product:{tag:"INSIDE THE APP",a:"Two catalogs.",b:"One build.",body:"Minify handles performance and game tools. Wardrobe covers heroes, HUDs, effects, and audio. They meet only when you build."},
    minify:{tag:"MINIFY · FUNCTIONAL MODS",a:"Remove the noise.",b:"Keep the game.",body:"Every mod includes a before-and-after view, a clear description, and the exact resources it changes.",items:["Search and seven categories","Author and source stay visible","Conflicts appear before install"],link:"See the flow"},
    wardrobe:{tag:"WARDROBE · VISUAL MODS",a:"Shape the look",b:"of your game.",body:"Browse 1,135 options for heroes, interface, world, effects, and audio. Your selection stays put while you move between categories.",items:["Search by hero and category","Preview the selected variant","Compatibility and author details"]},
    journey:{tag:"HOW BETTERFY WORKS",a:"From selection",b:"to launch.",body:"Four short steps. At each one, you know what is happening and what comes next.",stage:"STEP",next:"Next step",restart:"Start again"},
    account:{tag:"BETTERFY PROFILE",player:"Player",offline:"Telegram is not connected",setup:"Set up",browser:"This browser",browserState:"Not signed in yet",current:"CURRENT",app:"Windows app",appState:"Waiting for approval",notConnected:"NOT CONNECTED",section:"PROFILE AND DEVICES",a:"Builds stay close.",b:"Access stays yours.",body:"Your profile keeps builds and connected devices together. Sign-in is confirmed with a one-time Telegram code.",open:"Open profile"},
    download:{tag:"WINDOWS · EARLY ACCESS",a:"Try BetterFy",b:"with your Dota.",body:"The test build is available for Windows 10 and 11. A BetterFy profile is required to download.",cta:"Download BetterFy",versions:"GitHub releases",title:"Download BetterFy",checking:"Checking your platform and the latest test build.",system:"Windows 10/11 · x64",found:"Latest build found",login:"Sign in with Telegram",continue:"Sign in and continue",error:"The build could not be opened. Please try again.",version:"VERSION",package:"FILE",published:"UPDATED",locating:"Looking for the latest build…",unavailable:"No public build has been released yet"},
    auth:{tag:"BETTERFY PROFILE",title:"Sign in",body:"Get a code in Telegram and enter it here. BetterFy never asks for access to your chats.",access:"ACCESS",notConnected:"Not connected",sessions:"SESSIONS",none:"No active sessions",code:"CODE",minutes:"10 minutes",get:"Get a code in Telegram",have:"I already have a code",label:"Confirmation code",enter:"Sign in",oneTime:"The code is single-use and valid for 10 minutes.",safe:"You stay in control.",safeText:"New devices are approved separately, and any session can be ended from your profile.",security:"Security",source:"Source code",checking:"Checking…",invalid:"The code is invalid or has already been used.",active:"Active devices",until:"until",revoke:"End",signout:"Sign out",early:"Early access",premium:"Premium"},
    footer:{tag:"Your Dota. Only better.",product:"PRODUCT",project:"PROJECT",features:"Features",process:"How it works",telegram:"Telegram",roadmap:"Roadmap",legal:"Independent project. Not affiliated with Valve Corporation."}
  }
} as const;

const journeyCopy = {
  ru:[
    {n:"01",title:"Выбрать",label:"12 модов",heading:"Собери свой набор.",text:"Minify и гардероб находятся в отдельных каталогах. У каждого мода есть превью, автор и список изменений.",points:["Фильтры по типу и герою","Превью до добавления","Выбор сохраняется сразу"],icon:Search},
    {n:"02",title:"Проверить",label:"всё чисто",heading:"Узнай результат заранее.",text:"BetterFy покажет замены, зависимости и конфликты до того, как сборка коснётся файлов Dota 2.",points:["Проверка каждой замены","Конфликт виден рядом с модом","Понятный итог проверки"],icon:FileCheck2},
    {n:"03",title:"Собрать",label:"готово",heading:"Подтверди и запускай.",text:"После проверки остаётся один понятный план. BetterFy применяет его по шагам и сохраняет журнал операции.",points:["Один итоговый план","Статус каждого шага","Сборка привязана к профилю"],icon:PackageCheck},
    {n:"04",title:"Откатить",label:"безопасно",heading:"Верни всё как было.",text:"Если захочешь сменить набор или вернуть исходные файлы, BetterFy использует сохранённый журнал сборки.",points:["Проверка перед откатом","Чужие изменения не стираются","Повторная сборка без ручной чистки"],icon:RotateCcw}
  ],
  en:[
    {n:"01",title:"Select",label:"12 mods",heading:"Choose your setup.",text:"Minify and Wardrobe live in separate catalogs. Every mod has a preview, author, and change list.",points:["Filters by type and hero","Preview before adding","Selection saves instantly"],icon:Search},
    {n:"02",title:"Check",label:"all clear",heading:"Know the result first.",text:"BetterFy shows replacements, dependencies, and conflicts before the build touches Dota 2 files.",points:["Every replacement is checked","Conflicts sit beside the mod","A clear check summary"],icon:FileCheck2},
    {n:"03",title:"Build",label:"ready",heading:"Confirm and launch.",text:"After the check, one clear plan remains. BetterFy applies it step by step and keeps an operation log.",points:["One final plan","Status for every step","Build linked to your profile"],icon:PackageCheck},
    {n:"04",title:"Restore",label:"safe",heading:"Return to the original.",text:"When you change your setup or restore the game, BetterFy follows the saved build log.",points:["Check before restore","External changes stay safe","Rebuild without manual cleanup"],icon:RotateCcw}
  ]
} as const;

const Wordmark=({compact=false}:{compact?:boolean})=><span className={`wordmark ${compact?"compact":""}`} aria-label="BetterFy"><span className="wordmark-better">Better</span><span className="wordmark-fy">Fy</span></span>;

function tiltMove(event:PointerEvent<HTMLElement>){if(window.matchMedia("(prefers-reduced-motion: reduce)").matches||event.pointerType==="touch")return;const node=event.currentTarget,rect=node.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;node.style.setProperty("--tilt-x",`${(.5-y)*8}deg`);node.style.setProperty("--tilt-y",`${(x-.5)*10}deg`);node.style.setProperty("--light-x",`${x*100}%`);node.style.setProperty("--light-y",`${y*100}%`)}
function tiltReset(event:PointerEvent<HTMLElement>){event.currentTarget.style.setProperty("--tilt-x","0deg");event.currentTarget.style.setProperty("--tilt-y","0deg")}
function safeReleaseUrl(value?:string){try{if(!value)return null;const url=new URL(value);return url.protocol==="https:"&&url.hostname==="github.com"&&url.pathname.startsWith("/zori-xyz/BetterFy/releases/")?url.toString():null}catch{return null}}

function ProfilePanel({language,t,close,stage,session,token,code,setCode,error,verify,avatar,sessions,revoke,logout}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;stage:AuthStage;session:WebSession|null;token:string|null;code:string;setCode:(v:string)=>void;error:string;verify:()=>void;avatar:string|null;sessions:DeviceSession[];revoke:(s:DeviceSession)=>void;logout:()=>void}){
  const access=session?.accessTier==="premium"?t.auth.premium:t.auth.early;
  return <div className="modal-backdrop" onMouseDown={close}><section className="profile-panel" role="dialog" aria-modal="true" aria-labelledby="profile-title" onMouseDown={e=>e.stopPropagation()}>
    <button className="modal-close" onClick={close} aria-label="Close"><X size={17}/></button>
    <div className="profile-head"><div className="profile-avatar">{avatar?<img src={avatar} alt=""/>:<UserRound size={34}/>}<span>BF</span></div><div><p className="micro">{t.auth.tag}</p><h2 id="profile-title">{session?session.displayName:t.auth.title}</h2><p>{session?(session.username?`@${session.username} · ${access}`:access):t.auth.body}</p></div></div>
    {session?<>
      <div className="profile-summary"><div><ShieldCheck size={18}/><span>{t.auth.access}</span><strong>{access}</strong></div><div><Monitor size={18}/><span>{t.auth.sessions}</span><strong>{sessions.length}</strong></div><div><KeyRound size={18}/><span>ID</span><strong>{session.userId.slice(0,8)}</strong></div></div>
      <div className="device-list"><h3>{t.auth.active}</h3>{sessions.map(item=><article key={item.sessionId}><span className="device-icon">{item.clientKind==="desktop"?<Gamepad2 size={17}/>:<Monitor size={17}/>}</span><div><b>{item.clientKind==="desktop"?"BetterFy Windows":language==="ru"?"Веб-сайт BetterFy":"BetterFy website"}</b><small>{t.auth.until} {new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(item.expiresAt*1000))}</small></div>{item.current?<em>{t.account.current}</em>:<button onClick={()=>revoke(item)}>{t.auth.revoke}</button>}</article>)}</div>
      <button className="signout-button" onClick={logout}><LogOut size={15}/>{t.auth.signout}</button>
    </>:<>
      <div className="profile-summary"><div><ShieldCheck size={18}/><span>{t.auth.access}</span><strong>{t.auth.notConnected}</strong></div><div><Monitor size={18}/><span>{t.auth.sessions}</span><strong>{t.auth.none}</strong></div><div><KeyRound size={18}/><span>{t.auth.code}</span><strong>{t.auth.minutes}</strong></div></div>
      <a className="action telegram" href={bot} target="_blank" rel="noreferrer" onClick={()=>setCode("")}><span className="action-icon"><Send size={17}/></span><b>{t.auth.get}</b><ExternalLink size={16}/></a>
      {stage==="idle"&&<button className="have-code-button" type="button" onClick={()=>setCode("")}><KeyRound size={14}/>{t.auth.have}</button>}
      {(stage==="code"||stage==="verifying")&&<form className="code-row otp-form" onSubmit={e=>{e.preventDefault();verify()}}><label htmlFor="access-code">{t.auth.label}</label><div className="code-entry"><div className="otp-control"><div className="otp-slots" aria-hidden="true">{Array.from({length:6},(_,index)=><span key={index} className={code.length===index?"current":""}>{code[index]||""}</span>)}</div><input className="otp-input" id="access-code" aria-label={t.auth.label} inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} disabled={stage==="verifying"}/></div><button className="otp-submit" type="submit" disabled={stage==="verifying"||code.length!==6}>{stage==="verifying"?t.auth.checking:t.auth.enter}<ArrowRight size={15}/></button></div><small className={error?"is-error":""}>{error||t.auth.oneTime}</small></form>}
      <div className="profile-note"><ShieldCheck size={16}/><p><b>{t.auth.safe}</b><span>{t.auth.safeText}</span></p></div>
    </>}
    <div className="profile-links"><a href={`${repo}/blob/main/docs/IDENTITY_AND_WEB_ARCHITECTURE.md`}>{t.auth.security}<ExternalLink size={12}/></a><a href={repo}>{t.auth.source}<ExternalLink size={12}/></a></div>
  </section></div>
}

function DownloadPanel({language,t,close,session,release,releaseLoading,openProfile,download,error}:{language:Language;t:typeof copy.ru|typeof copy.en;close:()=>void;session:WebSession|null;release:ReleaseMeta|null;releaseLoading:boolean;openProfile:()=>void;download:()=>void;error:string}){
  const date=release?new Intl.DateTimeFormat(language==="ru"?"ru-RU":"en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(release.publishedAt)):"—";
  const size=release?`${(release.size/1048576).toFixed(1)} MB`:"—";
  return <div className="modal-backdrop" onMouseDown={close}><section className="download-panel" role="dialog" aria-modal="true" aria-labelledby="download-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close} aria-label="Close"><X size={17}/></button><div className="download-mark"><Wordmark/></div><p className="micro">WINDOWS · EARLY ACCESS</p><h2 id="download-title">{t.download.title}</h2><p>{t.download.checking}</p><div className="download-checks"><span className="active"><i><Check size={14}/></i>{t.download.system}</span><span className={release?"active":""}><i>{release?<Check size={14}/>:"2"}</i>{releaseLoading?t.download.locating:release?t.download.found:t.download.unavailable}</span><span className={session?"active":""}><i>{session?<Check size={14}/>:"3"}</i>{session?session.displayName:t.download.login}</span></div>{release&&<div className="release-details"><span><small>{t.download.version}</small><b>{release.version}</b></span><span><small>{t.download.package}</small><b title={release.fileName}>{size}</b></span><span><small>{t.download.published}</small><b>{date}</b></span></div>}<button className="action primary wide" onClick={session?download:openProfile} disabled={releaseLoading||(!release&&Boolean(session))}><span className="action-icon">{session?<ArrowDownToLine size={17}/>:<CircleUserRound size={17}/>}</span><b>{session?t.download.cta:t.download.continue}</b><ArrowRight size={17}/></button>{error&&<p className="download-error" role="alert">{error}</p>}<a className="quiet-link" href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></section></div>
}

export default function Site(){
  const[language,setLanguage]=useState<Language>("ru"),[profile,setProfile]=useState(false),[download,setDownload]=useState(false),[active,setActive]=useState(0),[darkWardrobe,setDarkWardrobe]=useState(false);
  const[authStage,setAuthStage]=useState<AuthStage>("checking"),[authSession,setAuthSession]=useState<WebSession|null>(null),[sessionToken,setSessionToken]=useState<string|null>(null),[authCode,setAuthCode]=useState(""),[authError,setAuthError]=useState(""),[avatarUrl,setAvatarUrl]=useState<string|null>(null),[deviceSessions,setDeviceSessions]=useState<DeviceSession[]>([]),[downloadError,setDownloadError]=useState(""),[releaseMeta,setReleaseMeta]=useState<ReleaseMeta|null>(null),[releaseLoading,setReleaseLoading]=useState(false);
  const t=copy[language],steps=journeyCopy[language],step=useMemo(()=>steps[active],[steps,active]),StepIcon=step.icon;
  const wardrobeImage=asset(language==="en"?(darkWardrobe?"poster-wardrobe-en-dark.webp":"poster-wardrobe-en-light.webp"):(darkWardrobe?"poster-wardrobe-ru-dark.webp":"poster-wardrobe.webp"));
  const minifyImage=asset(language==="en"?"poster-minify-en.webp":"poster-minify.webp");
  const homeImage=asset(language==="en"?"app-home-dark-en.webp":"app-home-original.webp");

  useEffect(()=>{try{const saved=localStorage.getItem("betterfy-site-language");if(saved==="en")setLanguage("en");const stored=sessionStorage.getItem(sessionKey);if(stored)setSessionToken(stored);else setAuthStage("idle")}catch{setAuthStage("idle")}},[]);
  useEffect(()=>{document.documentElement.lang=language;try{localStorage.setItem("betterfy-site-language",language)}catch{}},[language]);
  useEffect(()=>{document.body.style.overflow=(profile||download)?"hidden":"";return()=>{document.body.style.overflow=""}},[profile,download]);
  useEffect(()=>{if(!profile&&!download)return;const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"){setProfile(false);setDownload(false)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[profile,download]);
  useEffect(()=>{const nodes=Array.from(document.querySelectorAll<HTMLElement>(".reveal"));if(matchMedia("(prefers-reduced-motion: reduce)").matches){nodes.forEach(n=>n.classList.add("is-visible"));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:"0px 0px -7%"});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);
  useEffect(()=>{if(!sessionToken){setAuthSession(null);setAuthStage("idle");return}const controller=new AbortController();setAuthStage("checking");fetch(new URL("/v1/session/profile",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<WebSession>}).then(data=>{setAuthSession(data);setAuthStage("ready")}).catch(e=>{if(e instanceof DOMException&&e.name==="AbortError")return;try{sessionStorage.removeItem(sessionKey)}catch{}setSessionToken(null);setAuthStage("idle")});return()=>controller.abort()},[sessionToken]);
  useEffect(()=>{if(!sessionToken||!authSession?.avatarAvailable){setAvatarUrl(null);return}const controller=new AbortController();let objectUrl:string|null=null;fetch(new URL("/v1/session/avatar",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.blob():Promise.reject()).then(blob=>{objectUrl=URL.createObjectURL(blob);setAvatarUrl(objectUrl)}).catch(()=>setAvatarUrl(null));return()=>{controller.abort();if(objectUrl)URL.revokeObjectURL(objectUrl)}},[sessionToken,authSession?.avatarAvailable]);
  useEffect(()=>{if(!profile||!sessionToken||!authSession)return;const controller=new AbortController();fetch(new URL("/v1/session/devices",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit",signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then((data:{sessions?:DeviceSession[]})=>setDeviceSessions(Array.isArray(data.sessions)?data.sessions:[])).catch(()=>setDeviceSessions([]));return()=>controller.abort()},[profile,sessionToken,authSession]);
  useEffect(()=>{if(!download||releaseMeta)return;const controller=new AbortController();setReleaseLoading(true);fetch("https://api.github.com/repos/zori-xyz/BetterFy/releases/latest",{headers:{Accept:"application/vnd.github+json"},signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then((data:{tag_name?:string;published_at?:string;assets?:Array<{name?:string;size?:number}>})=>{const asset=data.assets?.find(item=>/\.(exe|msi)$/i.test(item.name||""))||data.assets?.[0];if(!data.tag_name||!data.published_at||!asset?.name||!asset.size)throw new Error();setReleaseMeta({version:data.tag_name,fileName:asset.name,size:asset.size,publishedAt:data.published_at})}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setReleaseMeta(null)}).finally(()=>setReleaseLoading(false));return()=>controller.abort()},[download,releaseMeta]);

  const verifyCode=async()=>{if(!/^\d{6}$/.test(authCode)){setAuthError(t.auth.invalid);return}setAuthStage("verifying");setAuthError("");try{const response=await fetch(new URL("/v1/auth/telegram/code",authUrl),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:authCode,clientKind:"web"}),credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json() as WebSession&{sessionToken?:string};if(!data.sessionToken||!data.displayName)throw new Error();sessionStorage.setItem(sessionKey,data.sessionToken);setSessionToken(data.sessionToken);setAuthSession(data);setAuthStage("ready");setAuthCode("")}catch{setAuthStage("code");setAuthError(t.auth.invalid)}};
  const revoke=async(item:DeviceSession)=>{if(!sessionToken)return;try{const response=await fetch(new URL("/v1/session/devices/revoke",authUrl),{method:"POST",headers:{Authorization:`Bearer ${sessionToken}`,"content-type":"application/json"},body:JSON.stringify({sessionId:item.sessionId}),credentials:"omit"});if(!response.ok)throw new Error();if(item.current){logout();return}setDeviceSessions(v=>v.filter(x=>x.sessionId!==item.sessionId))}catch{}};
  const logout=()=>{const token=sessionToken;try{sessionStorage.removeItem(sessionKey)}catch{}setSessionToken(null);setAuthSession(null);setAvatarUrl(null);setDeviceSessions([]);setAuthStage("idle");if(token)fetch(new URL("/v1/session/logout",authUrl),{method:"POST",headers:{Authorization:`Bearer ${token}`},credentials:"omit"}).catch(()=>undefined)};
  const downloadBuild=async()=>{setDownloadError("");if(!sessionToken||!authSession){setDownload(false);setProfile(true);return}try{const response=await fetch(new URL("/v1/releases/latest",authUrl),{headers:{Authorization:`Bearer ${sessionToken}`},credentials:"omit"});if(!response.ok)throw new Error();const data=await response.json() as{downloadUrl?:string};const url=safeReleaseUrl(data.downloadUrl);if(!url)throw new Error();window.location.assign(url)}catch{setDownloadError(t.download.error)}};

  return <><header className="site-header"><a href="#top"><Wordmark compact/></a><nav aria-label="Navigation"><a href="#product">{t.nav[0]}</a><a href="#journey">{t.nav[1]}</a><a href="#download">{t.nav[2]}</a></nav><div className="header-actions"><div className="language-switch" aria-label="Language"><button className={language==="ru"?"active":""} onClick={()=>setLanguage("ru")}>RU</button><button className={language==="en"?"active":""} onClick={()=>setLanguage("en")}>EN</button></div><span className="live"><i/>{t.early}</span><button className="profile-button" onClick={()=>setProfile(true)}>{avatarUrl?<img src={avatarUrl} alt=""/>:<CircleUserRound size={16}/>} {authSession?.displayName||t.profile}</button></div></header>
  <main id="top"><section className="hero shell"><div className="hero-copy"><p className="eyebrow"><Sparkles size={13}/>{t.hero.tag}</p><h1>{t.hero.a}<br/><strong>{t.hero.b}</strong></h1><p className="lead">{t.hero.body}</p><div className="hero-actions"><button className="action primary" onClick={()=>document.querySelector("#product")?.scrollIntoView({behavior:"smooth"})}><span className="action-icon"><Layers3 size={18}/></span><b>{t.hero.cta}</b><ArrowRight size={18}/></button><button className="text-action" onClick={()=>setDownload(true)}>{t.hero.download}<Download size={15}/></button></div><div className="trust-row"><span><i className="ready-dot"/>{t.hero.trust}</span><span>{t.hero.open}</span></div></div><figure className="hero-poster tilt-card app-screen" onPointerMove={tiltMove} onPointerLeave={tiltReset}><div className="poster-glow"/><img src={homeImage} alt="BetterFy home"/><figcaption><span>{t.hero.card}</span><b>{t.hero.cardText}</b></figcaption></figure></section>
  <section className="state-rail shell reveal" aria-label="Build flow">{t.rail.map((item,i)=><Fragment key={item[0]}><div><span>{String(i+1).padStart(2,"0")}</span><b>{item[0]}</b><small>{item[1]}</small></div>{i<3&&<i/>}</Fragment>)}</section>
  <section className="product shell" id="product"><div className="section-intro reveal"><p className="eyebrow"><span>01</span>{t.product.tag}</p><h2>{t.product.a}<br/><strong>{t.product.b}</strong></h2><p>{t.product.body}</p></div><article className="feature dark-feature reveal"><div className="feature-copy"><p className="micro">{t.minify.tag}</p><h3>{t.minify.a}<br/>{t.minify.b}</h3><p>{t.minify.body}</p><ul>{t.minify.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><a href="#journey">{t.minify.link}<ChevronRight size={14}/></a></div><button className="poster-button tilt-card" onPointerMove={tiltMove} onPointerLeave={tiltReset} onClick={()=>window.open(minifyImage,"_blank")} aria-label="Minify"><img key={minifyImage} src={minifyImage} alt="Minify"/><span>{t.open}<ExternalLink size={12}/></span></button></article>
  <article className={`feature light-feature reveal is-visible ${darkWardrobe?"is-dark-preview":""}`}><button className="poster-button tilt-card wardrobe-screen" onPointerMove={tiltMove} onPointerLeave={tiltReset} onClick={()=>window.open(wardrobeImage,"_blank")} aria-label="Wardrobe"><img key={wardrobeImage} src={wardrobeImage} alt="BetterFy Wardrobe"/><span>{t.open}<ExternalLink size={12}/></span></button><div className="feature-copy"><div className="theme-switch" role="group" aria-label="Theme"><button type="button" aria-pressed={!darkWardrobe} className={!darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(false)}>{t.light}</button><button type="button" aria-pressed={darkWardrobe} className={darkWardrobe?"active":""} onClick={()=>setDarkWardrobe(true)}>{t.dark}</button></div><p className="micro">{t.wardrobe.tag}</p><h3>{t.wardrobe.a}<br/>{t.wardrobe.b}</h3><p>{t.wardrobe.body}</p><ul>{t.wardrobe.items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></article></section>
  <section className="journey" id="journey"><div className="shell"><div className="journey-intro reveal"><p className="eyebrow"><span>02</span>{t.journey.tag}</p><h2>{t.journey.a}<br/><strong>{t.journey.b}</strong></h2><p>{t.journey.body}</p></div><div className="journey-board reveal"><div className="journey-tabs" role="tablist">{steps.map((item,i)=>{const Icon=item.icon;return <button key={item.n} role="tab" aria-selected={active===i} onClick={()=>setActive(i)}><span className="journey-number">{item.n}</span><i><Icon size={18}/></i><b>{item.title}</b><small>{item.label}</small></button>})}</div><div className="journey-detail" key={`${language}-${step.n}`}><div className="stage-visual"><div className="stage-logo"><Wordmark compact/></div><StepIcon size={54}/><span>{step.n} / 04</span></div><div className="stage-copy"><p className="micro">{t.journey.stage} {step.n}</p><h3>{step.heading}</h3><p>{step.text}</p><ul>{step.points.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><button onClick={()=>setActive(active===3?0:active+1)}>{active===3?t.journey.restart:t.journey.next}<ArrowRight size={16}/></button></div></div><div className="journey-progress"><i style={{width:`${25*(active+1)}%`}}/></div></div></div></section>
  <section className="account shell reveal"><div className="account-visual"><div className="account-card"><div className="account-avatar">{avatarUrl?<img src={avatarUrl} alt=""/>:<UserRound size={27}/>}</div><div><p className="micro">{t.account.tag}</p><h3>{authSession?.displayName||t.account.player}</h3><span>{authSession?(authSession.username?`@${authSession.username}`:t.auth.early):t.account.offline}</span></div><button onClick={()=>setProfile(true)}>{t.account.setup}<ArrowRight size={14}/></button></div><div className="session-row"><Monitor size={17}/><div><b>{t.account.browser}</b><span>{authSession?t.auth.safe:t.account.browserState}</span></div><em>{t.account.current}</em></div><div className="session-row"><Gamepad2 size={17}/><div><b>{t.account.app}</b><span>{t.account.appState}</span></div><em>{t.account.notConnected}</em></div></div><div className="account-copy"><p className="eyebrow"><span>03</span>{t.account.section}</p><h2>{t.account.a}<br/><strong>{t.account.b}</strong></h2><p>{t.account.body}</p><button className="action secondary" onClick={()=>setProfile(true)}><span className="action-icon"><CircleUserRound size={18}/></span><b>{t.account.open}</b><ArrowRight size={18}/></button></div></section>
  <section className="download-section" id="download"><div className="download-aura"/><div className="shell download-inner reveal"><div><p className="eyebrow"><span>04</span>{t.download.tag}</p><h2>{t.download.a}<br/><strong>{t.download.b}</strong></h2><p>{t.download.body}</p></div><div className="download-cta"><button className="action primary huge" onClick={()=>setDownload(true)}><span className="action-icon"><ArrowDownToLine size={19}/></span><b>{t.download.cta}</b><ArrowRight size={19}/></button><span>{t.download.system} · Early Access</span><a href={`${repo}/releases`}>{t.download.versions}<ExternalLink size={12}/></a></div></div></section>
  <footer className="site-footer shell"><div><Wordmark/><p>{t.footer.tag}</p></div><div><b>{t.footer.product}</b><a href="#product">{t.footer.features}</a><a href="#journey">{t.footer.process}</a><button onClick={()=>setProfile(true)}>{t.profile}</button></div><div><b>{t.footer.project}</b><a href={repo}>GitHub<ExternalLink size={11}/></a><a href={bot}>{t.footer.telegram}<ExternalLink size={11}/></a><a href={`${repo}/blob/main/docs/ROADMAP.md`}>{t.footer.roadmap}<ExternalLink size={11}/></a></div><span>{t.footer.legal}</span></footer></main>
  {profile&&<ProfilePanel language={language} t={t} close={()=>setProfile(false)} stage={authStage} session={authSession} token={sessionToken} code={authCode} setCode={v=>{setAuthCode(v);setAuthError("");setAuthStage("code")}} error={authError} verify={verifyCode} avatar={avatarUrl} sessions={deviceSessions} revoke={revoke} logout={logout}/>} {download&&<DownloadPanel language={language} t={t} close={()=>setDownload(false)} session={authSession} release={releaseMeta} releaseLoading={releaseLoading} openProfile={()=>{setDownload(false);setProfile(true)}} download={downloadBuild} error={downloadError}/>}</>;
}
